USE Aduana
GO
SET ANSI_NULLS, QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE SlamNetImp_spI_Copia
(
	@REFORG varchar(10)='',
	@PREF varchar(10)='',
	@Pedimento varchar(50)='',
	@CliID int=0,
	@nPrefijo VARCHAR(5)='',
	@RefManual varchar(10)=''
)
WITH ENCRYPTION
AS
BEGIN

BEGIN TRY

	BEGIN TRANSACTION

	IF NOT EXISTS(SELECT bodreferencia FROM tblbod WHERE bodreferencia=@REFORG AND pref=@PREF)
	BEGIN
		RAISERROR ('La referencia que intenta copiar NO existe en esta sucursal, por favor de verificarlo!!!',19,1); 
	END

	DECLARE @IMPEXP BIT
	SET @IMPEXP = (SELECT TRAIMPEXP FROM TRAFICO WHERE TRAREFERENCIA=@REFORG AND PREF=@PREF)
	
	IF EXISTS(SELECT pref FROM tblcomp WHERE pref IN ('T3628240','T3628800'))
		SET @nPrefijo=(SELECT SUBSTRING(@REFORG,0,4))
	else
		IF EXISTS(Select PREFIJO From TBLCOMP Where PREFIJO = @nPrefijo )
				Set @IMPEXP = 1
		ELSE
			IF EXISTS(Select PREFIJOEXPO From TBLCOMP Where PREFIJOEXPO = @nPrefijo )
				Set @IMPEXP = 0
	/*ASIGNACION DE REFERENCIA*/
	DECLARE @Referencia VARCHAR(10)
	IF OBJECT_ID('tempdb..#TEMPREF') IS NOT NULL 
	BEGIN
		DROP TABLE #TEMPREF;
	END
	CREATE TABLE #TEMPREF (campo varchar(100))
	INSERT INTO #TEMPREF
	EXEC dbo.SlamNetImp_sp_GetReferencia @PREF,@RefManual,@IMPEXP,@nPrefijo;
	SET @Referencia=(SELECT campo FROM #TEMPREF);

	IF @Referencia IS NULL OR @Referencia = ''
	BEGIN
		RAISERROR ('El numero de referencia no fue posible asignarlo!!!',16,1); 
	END

	DROP TABLE #TEMPREF;
	/*ASIGNACION DE REFERENCIA*/

	DECLARE @FACIDNEW NUMERIC(10)
	DECLARE @FACNUMTEMP VARCHAR(20)
	DECLARE @FACIDTEMP NUMERIC(10)

	DECLARE @ID		int
	DECLARE @TRAFICO_ID INT
	DECLARE @FACGSUCURSAL CHAR(1)
	DECLARE @RefN CHAR(1)
	DECLARE @CLAVEORG VARCHAR (2)
	DECLARE @Error NVARCHAR(500)

	SELECT @CLAVEORG = tblNotaRevGen.CLAVEPED  FROM TBLNOTAREVGEN WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- BODEGA
	INSERT INTO [tblBod]
		([bodEntrada],[bodReferencia],[bodNumRef],[BODEMB],[bodtipemb],[bodtiptra]
		,[bodcli],[bodprocli],[bodfecha],[bodfle],[bodimpfle],[bodtipfle]
		,[bodCHEQUE],[bodCOD],[bodtipCOD],[bodchequeCOD],[bodbno],[bodcaja]
		,[bodhora],[bodfechac],[bodhorac],[boddescmer],[bodvalmer],[bodnopedido]
		,[bodbultos],[bodpesolbs],[bodseccion],[bodUsuario],[bodDescargo],[bodVerifico]
		,[bodcomen1],[bodcomen2],[bodAnota1],[bodfoto1],[bodfoto2],[bodBandera]
		,[bodfoto],[bodCancelado],[bodUsada],[BodDescCaja],[BodRevisado],[BodMercTran]
		,[BODINBOND],[BODDESTINO],[BODSALES],[BODSHIPPING],[BODLORIGEN],[BODFORIGEN]
		,[CON_PROD],[EMBALAJE],[LOTES],[CERTIFICADO],[TEMPERATURA],[BODCONSIGNA_ID]
		,[ULTIMA_MOD],[PORLLEGAR],[CLIPROV],[BODVIRTUAL],[BODTLC],[BODRECIBIDO]
		,[BODTURNO],[BODESTATUS],[BODGUIAP],[BODORIGEN],[BODCONCARGA],[BODSHIPID]
		,[BODFALTALE],[BODFALTAFAC],[BODFALTAPER],[BODFALTANOM],[BODFALTAORDEN]
		,[BODLLEGODAN],[BODLLEGOINC],[BODPRECIOINC],[BODCARTDAN],[BODGO],[BODINBOND2]
		,[BODPEDIMENTO],[BODPORIGEN],[BODSIMULADOR],[BODADUANA],[BODMERCAFAL]
		,[BODCODIGO],[BODPACKLIST],[BODSHIPMENT],[BODHCERTIFICA],[BODNAFTA],[BODMSDS]
		,[BODRCERTIFICA],[BODCOA],[BODRRECEPCION],[BODFNOTIFICA],[BODFCERTIFICA]
		,[BODHNOTIFICA],[BODRNOTIFICA],[BODRCARGA],[BODFENTRADA],[BODHENTRADA]
		,[BODRENTRADA],[BODRELABORACION],[BODRPAGO],[BODRSALBOD],[BODRSALPATIO]
		,[BODRCRUCE],[BODRSALADUANA],[BODRENTREGA],[BODCOMPRADOR],[BODRUTA]
		,[BODLOCALIDAD],[BODMARCA],[BODFEXPFURGON],[PREF],[FEPUNTO],[FSPUNTO]
		,[OBSPUNTO],[OPERPUNTO],[BODCATEGORIA],[BODEMBARCADOR_ID],[BODMATPEL]
		,[BODDISTRIBUCION],[FECHABILL],[BODMOVIL],[BODEJECUTIVOCUENTA],[TIPOIMPO]
		,[DESC_TIPOIMPO],[BODSYMBOLS],[BODNOMMT],[BODCLASEMT],[BODGEMT],[BODIDMT]
		,[BODFHCTAINST],[BODPDESTINO],[BODFREQPLANTA],[BODCODIGOGT],[BODCODIGOOPI]
		,[BODGRS],[BODANCHO],[BODLINEAREFOSA],[BODCAJAREFOSA],[BODOBSREFOSA]
		,[CODE_GV],[QUANTITY_GV],[BODHORARECIBO],[BODCLASIFICADO],[BODFECHAFONDEO]
		,[TEMPCAJA],[CONDLIMPIEZA],[FAUNANOCIVA],[LIBERADA],[RECHAZADA]
		,[PIEZAS],[BODPROICA],[BODCDIVISION],[BODCDESTINO],[R1],[BODDESTINA]
		,[BODDATENOTI],[BODDATESLP],[BODBODEGAAM],[BODNOM144],[BODMONEDA],[BODCONTROL]
		,[DOCBL],[DOCPL],[DOCCO],[DOCAQ],[DOCCNOM],[DOCOSD],[DOCEN]
		,[DOCES],[DOCME],[DOCFC],[BODPALETAPLASTICO],[MUESTRA],[INTERCOMPANY]
		,[CENTROCOSTOS],[REFCATEGORY],[GLACCOUNT],[BODDANANDA],[BODDANADA],[BODPERTENECEA]
		,[BODPERTENECEA_ID],[BOCOMEN2],[SERIE],[MODELO],[BODPREENTRADA])
	SELECT
		 [bodEntrada],@Referencia,@Referencia,[BODEMB],[bodtipemb],[bodtiptra]
		,[bodcli],[bodprocli],[bodfecha],[bodfle],[bodimpfle],[bodtipfle]
		,[bodCHEQUE],[bodCOD],[bodtipCOD],[bodchequeCOD],[bodbno],[bodcaja]
		,[bodhora],[bodfechac],[bodhorac],[boddescmer],[bodvalmer],[bodnopedido]
		,[bodbultos],[bodpesolbs],[bodseccion],[bodUsuario],[bodDescargo],[bodVerifico]
		,[bodcomen1],[bodcomen2],[bodAnota1],[bodfoto1],[bodfoto2],[bodBandera]
		,[bodfoto],[bodCancelado],[bodUsada],[BodDescCaja],[BodRevisado],[BodMercTran]
		,[BODINBOND],[BODDESTINO],[BODSALES],[BODSHIPPING],[BODLORIGEN],[BODFORIGEN]
		,[CON_PROD],[EMBALAJE],[LOTES],[CERTIFICADO],[TEMPERATURA],[BODCONSIGNA_ID]
		,CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),[PORLLEGAR],[CLIPROV],[BODVIRTUAL],[BODTLC],[BODRECIBIDO]
		,[BODTURNO],[BODESTATUS],[BODGUIAP],[BODORIGEN],[BODCONCARGA],[BODSHIPID]
		,[BODFALTALE],[BODFALTAFAC],[BODFALTAPER],[BODFALTANOM],[BODFALTAORDEN]
		,[BODLLEGODAN],[BODLLEGOINC],[BODPRECIOINC],[BODCARTDAN],[BODGO],[BODINBOND2]
		,Null--@Pedimento--[BODPEDIMENTO]
		,[BODPORIGEN],[BODSIMULADOR],[BODADUANA],[BODMERCAFAL]
		,[BODCODIGO],[BODPACKLIST],[BODSHIPMENT],[BODHCERTIFICA],[BODNAFTA],[BODMSDS]
		,[BODRCERTIFICA],[BODCOA],[BODRRECEPCION],[BODFNOTIFICA],[BODFCERTIFICA]
		,[BODHNOTIFICA],[BODRNOTIFICA],[BODRCARGA],[BODFENTRADA],[BODHENTRADA]
		,[BODRENTRADA],[BODRELABORACION],[BODRPAGO],[BODRSALBOD],[BODRSALPATIO]
		,[BODRCRUCE],[BODRSALADUANA],[BODRENTREGA],[BODCOMPRADOR],[BODRUTA]
		,[BODLOCALIDAD],[BODMARCA],[BODFEXPFURGON],[PREF],[FEPUNTO],[FSPUNTO]
		,[OBSPUNTO],[OPERPUNTO],[BODCATEGORIA],[BODEMBARCADOR_ID],[BODMATPEL]
		,[BODDISTRIBUCION],[FECHABILL],[BODMOVIL],[BODEJECUTIVOCUENTA],[TIPOIMPO]
		,[DESC_TIPOIMPO],[BODSYMBOLS],[BODNOMMT],[BODCLASEMT],[BODGEMT],[BODIDMT]
		,[BODFHCTAINST],[BODPDESTINO],[BODFREQPLANTA],[BODCODIGOGT],[BODCODIGOOPI]
		,[BODGRS],[BODANCHO],[BODLINEAREFOSA],[BODCAJAREFOSA],[BODOBSREFOSA]
		,[CODE_GV],[QUANTITY_GV],[BODHORARECIBO],[BODCLASIFICADO],[BODFECHAFONDEO]
		,[TEMPCAJA],[CONDLIMPIEZA],[FAUNANOCIVA],[LIBERADA],[RECHAZADA]
		,[PIEZAS],[BODPROICA],[BODCDIVISION],[BODCDESTINO],[R1],[BODDESTINA]
		,[BODDATENOTI],[BODDATESLP],[BODBODEGAAM],[BODNOM144],[BODMONEDA],[BODCONTROL]
		,[DOCBL],[DOCPL],[DOCCO],[DOCAQ],[DOCCNOM],[DOCOSD],[DOCEN]
		,[DOCES],[DOCME],[DOCFC],[BODPALETAPLASTICO],[MUESTRA],[INTERCOMPANY]
		,[CENTROCOSTOS],[REFCATEGORY],[GLACCOUNT],[BODDANANDA],[BODDANADA],[BODPERTENECEA]
		,[BODPERTENECEA_ID],[BOCOMEN2],[SERIE],[MODELO],[BODPREENTRADA]
	FROM TBLBOD
	WHERE BODREFERENCIA=@REFORG AND PREF=@PREF;

	DECLARE @Cli int, @Procli int, @Usuario int, @Consigna_id int

	SELECT @Cli=BODCLI,@Procli=BODPROCLI,@Usuario=bodUsuario, @Consigna_id=BODCONSIGNA_ID
	FROM TBLBOD WHERE BODREFERENCIA=@REFORG AND PREF=@PREF;

	-- TRAFICO
	INSERT INTO [Trafico]
	/*01*/([traReferencia],[traFechaAct],[traCli],[traProCli],[traRelacion],[traFechaCruce]
	/*02*/,[traHora],[traNumCaja],[traFechaProg],[traLineaMex],[traTalon],[traPedimento]
	/*03*/,[traNoAnti],[traTotImp],[traFechaClas],[traAnti],[traFechaSol],[traFechaAnti]
	/*04*/,[traRecAnti],[traImpExp],[traStatus],[traDescripcion],[traUsuario],[traNOBORRAR]
	/*05*/,[traConsolidado],[traObservaciones],[traCuenta],[traPrincipal],[TRASUB],[trasagar]
	/*06*/,[TRAFECHADOC],[TRASALDADO],[TRAFECHACTA],[TRAIMPCTA],[SHIPPER],[CERTIFICADO]
	/*07*/,[TRAFENTREGA],[TRAHENTREGA],[TRACONSIGNA_ID],[TIPO_IND],[ULTIMA_MOD],[TRAIMPTALON]
	/*08*/,[TRATALONCHEQUE],[TRATALONFECHA],[TRAHORACLAS],[TRAHORASOL],[TRAHORARECANT],[TRACUENTAMEX]
	/*09*/,[TRAFECHACTAMEX],[TRAIMPCTAMEX],[TRAROJO],[TRAREGIMEN],[TRAREGIMEN_ARTEVA],[TRASELLO1]
	/*10*/,[TRASELLO2],[TRASELLO3],[TRADESCCAJA],[TRAFECHAPAGO],[TRAROJO2],[TRACHOFER]
	/*11*/,[TRANSFER],[TRAQUIMICOS],[TRASININSTRUCCION],[TRAFECHAUNIKO],[TRAHORAUNIKO],[ULTIMOREQUISITOUNIKO]
	/*12*/,[TRAFSALIDA],[TRAHSALIDA],[TRAPDESTINO],[PEDREC],[ENVIO],[TRAOBSRECON]
	/*13*/,[TRAHORACARR],[TRACAMION_ID],[MULTIPROV],[TRAANTIREC],[NOEMBARQUE],[TRAADUANA]
	/*14*/,[TRAHORAPAGO],[TRAUSUARIO2],[TRAFGSSHIPDATE],[TRABORDEREDA],[TRABORDERETA],[TRANOTIFICATIONDATE]
	/*15*/,[TRANOTIFICATIONTIME],[TRADATEDELIVERYMXCARRIER],[TRATIMEDELIVERYMXCARRIER],[TRARDCEDA],[TRARDCETA],[TRARDCADA]
	/*16*/,[TRARDCATA],[TRARDCUNLOADDATE],[TRARDCUNLOADTIME],[TRAHORAACT],[TRASELLO4],[PREF]
	/*17*/,[TRATRENNUM],[TRAFECHASL],[TRACERRADO],[TRAFECHAINICARGA],[TRAFECHAFINCARGA],[TRAHORAINICARGA]
	/*18*/,[TRAHORAFINCARGA],[TRAROJO1FE],[TRAROJO1HE],[TRAROJO1FS],[TRAROJO1HS],[TRAROJO2FE]
	/*19*/,[TRAROJO2HE],[TRAROJO2FS],[TRAROJO2HS],[TRARCUMPF],[TRARCUMPH],[TRARELCARGA]
	/*20*/,[TRAHORADOC],[CERTIFICADODEANALISIS],[EDETYEM],[TRAPARTETD],[TRACANTIDADTD],[TRAPRECIOTD]
	/*21*/,[TRACONTENEDOR],[DOW_MODAL],[DOW_FSHIPMENTCONS],[DOW_HSHIPMENTCONS],[DOW_COMEN1],[DOW_COMEN2]
	/*22*/,[DOW_MED1],[DOW_MED2],[TRAINCI1],[TRAINCI2],[RELFACNO],[FIRMAELECPREVIO]
	/*23*/,[TRADESCTRAFICO],[MANIFIESTO],[PERSONAFIRMA],[FCARGADOGEN],[TRADESCARGA],[TRAHTTRANSBORDO]
	/*24*/,[TRAHERRTIGUIA],[TRAHPR],[HTTRANSBORDO],[HERRTIGUIA],[HPR],[TRACHOFERLC]
	/*25*/,[TRATRANSFERLC],[TRADESADUANADO],[TRAFEMATRACK],[TRAFLLEGADAGANCHAR],[TRAHLLEGADAGANCHAR],[TRAFROJOMEX]
	/*26*/,[TRAHROJOMEX],[TRAFVERDEMEX],[TRAHVERDEMEX],[TRAFROJOAME],[TRAHROJOAME],[TRAFVERDEAME]
	/*27*/,[TRAHVERDEAME],[TRAFENTREGAFINAL],[TRAHENTREGAFINAL],[TRAQUIENRECIBE],[TRASELLOS],[traValor]
	/*28*/,[TRADESTINA],[TRAFECHAOFICINA],[TRAFECHAFRONTERA],[TRAHORAOFICINA],[TRAHORAFRONTERA],[TRAHORAENTREGA]
	/*29*/,[TRADESPACHO],[TRASTATUSMANUAL],[TRAFAVISO],[TRAHAVISO],[TRAFPREFILE],[TRAHPREFILE]
	/*30*/,[BROKENSEAL],[NEWSEAL],[SEALCOLOR],[ARRIVALDATECUSTOM],[TRAENTMANI],[TRARECMANI]
	/*31*/,[TRAAAA],[MUESTREADO],[PRODMUES],[DETENIDO],[OBSPUNTO],[FDARELEASE]
	/*32*/,[FDARELEASEH],[ENVIOBL],[FSFFEDEST],[HSFFEDEST],[FLLDEST],[HLLDEST]
	/*33*/,[TRADATESLP],[TRADATENOTI],[TRATRANSFER],[ARRIVALTIMECUSTOM],[SEALRECIEVEDBY],[LDOFWHSE]
	/*34*/,[TRATIPOCONTENEDOR],[LDOHWHSE],[sealwasbroken],[TRAFSALPLA],[TRAHSALPLA],[plantaemb]
	/*35*/,[TRAHORARECMANI],[PIDI],[TRARECHMANI],[TRAENTHMANI],[NO_ENTRY],[PLACAS]
	/*36*/,[ESTADO_CAJA],[SERIE],[REFCLIENTE],[INBOND],[TRASELLONUEVO],[FACTURA]
	/*37*/,[OFECHASAL],[OHORASAL],[OFECHA_A26],[OHORA_A26],[OFECHA_OFICINA],[OHORA_OFICINA]
	/*38*/,[OPERADOR],[UNIDAD],[SCAC_CODE],[TRASELLOS_TRACKING],[SUCURSAL_TRACKING],[CITA_FECHACARGA_TRACKING]
	/*39*/,[CITA_HORACARGA_TRACKING],[PISTAS],[DOBLE_OPERADOR],[PAIS_CAJA],[TRADESTINO],[CONSM3])
	SELECT
	--/*01*/@Referencia,[traFechaAct],[traCli],[traProCli],[traRelacion],[traFechaCruce]
	/*01*/@Referencia,[traFechaAct],[traCli],[traProCli],NULL,NULL
	--/*02*/,[traHora],[traNumCaja],[traFechaProg],[traLineaMex],[traTalon],[traPedimento]
	/*02*/,NULL,NULL,NULL,[traLineaMex],[traTalon],@Pedimento
	--/*03*/,[traNoAnti],[traTotImp],[traFechaClas],[traAnti],[traFechaSol],[traFechaAnti]
	/*03*/,[traNoAnti],[traTotImp],NULL,[traAnti],[traFechaSol],[traFechaAnti]
	--/*04*/,[traRecAnti],[traImpExp],[traStatus],[traDescripcion],[traUsuario],[traNOBORRAR]
	/*04*/,[traRecAnti],@IMPEXP,'PENDIENTE SOLICITAR ANTICIPO',[traDescripcion],[traUsuario],[traNOBORRAR]
	--/*05*/,[traConsolidado],[traObservaciones],[traCuenta],[traPrincipal],[TRASUB],[trasagar]
	/*05*/,[traConsolidado],NULL,[traCuenta],[traPrincipal],[TRASUB],[trasagar]
	--/*06*/,[TRAFECHADOC],[TRASALDADO],[TRAFECHACTA],[TRAIMPCTA],[SHIPPER],[CERTIFICADO]
	/*06*/,[TRAFECHADOC],[TRASALDADO],[TRAFECHACTA],[TRAIMPCTA],0,[CERTIFICADO]
	/*07*/,[TRAFENTREGA],[TRAHENTREGA],[TRACONSIGNA_ID],[TIPO_IND],CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),[TRAIMPTALON]
	/*08*/,[TRATALONCHEQUE],[TRATALONFECHA],[TRAHORACLAS],[TRAHORASOL],[TRAHORARECANT],[TRACUENTAMEX]
	--/*09*/,[TRAFECHACTAMEX],[TRAIMPCTAMEX],[TRAROJO],[TRAREGIMEN],[TRAREGIMEN_ARTEVA],[TRASELLO1]
	/*09*/,[TRAFECHACTAMEX],[TRAIMPCTAMEX],[TRAROJO],[TRAREGIMEN],[TRAREGIMEN_ARTEVA],NULL
	--/*10*/,[TRASELLO2],[TRASELLO3],[TRADESCCAJA],[TRAFECHAPAGO],[TRAROJO2],[TRACHOFER]
	/*10*/,NULL,NULL,[TRADESCCAJA],Null,[TRAROJO2],[TRACHOFER]
	--/*11*/,[TRANSFER],[TRAQUIMICOS],[TRASININSTRUCCION],[TRAFECHAUNIKO],[TRAHORAUNIKO],[ULTIMOREQUISITOUNIKO]
	/*11*/,NULL,[TRAQUIMICOS],[TRASININSTRUCCION],[TRAFECHAUNIKO],[TRAHORAUNIKO],[ULTIMOREQUISITOUNIKO]
	--/*12*/,[TRAFSALIDA],[TRAHSALIDA],[TRAPDESTINO],[PEDREC],[ENVIO],[TRAOBSRECON]
	/*12*/,NULL,NULL,[TRAPDESTINO],[PEDREC],[ENVIO],[TRAOBSRECON]
	/*13*/,[TRAHORACARR],[TRACAMION_ID],[MULTIPROV],[TRAANTIREC],[NOEMBARQUE],[TRAADUANA]
	--/*14*/,[TRAHORAPAGO],[TRAUSUARIO2],[TRAFGSSHIPDATE],[TRABORDEREDA],[TRABORDERETA],[TRANOTIFICATIONDATE]
	/*14*/,Null,[TRAUSUARIO2],[TRAFGSSHIPDATE],[TRABORDEREDA],[TRABORDERETA],[TRANOTIFICATIONDATE]
	/*15*/,[TRANOTIFICATIONTIME],[TRADATEDELIVERYMXCARRIER],[TRATIMEDELIVERYMXCARRIER],[TRARDCEDA],[TRARDCETA],[TRARDCADA]
	/*16*/,[TRARDCATA],[TRARDCUNLOADDATE],[TRARDCUNLOADTIME],[TRAHORAACT],[TRASELLO4],[PREF]
	/*17*/,[TRATRENNUM],[TRAFECHASL],[TRACERRADO],[TRAFECHAINICARGA],[TRAFECHAFINCARGA],[TRAHORAINICARGA]
	/*18*/,[TRAHORAFINCARGA],[TRAROJO1FE],[TRAROJO1HE],[TRAROJO1FS],[TRAROJO1HS],[TRAROJO2FE]
	/*19*/,[TRAROJO2HE],[TRAROJO2FS],[TRAROJO2HS],[TRARCUMPF],[TRARCUMPH],[TRARELCARGA]
	/*20*/,[TRAHORADOC],[CERTIFICADODEANALISIS],[EDETYEM],[TRAPARTETD],[TRACANTIDADTD],[TRAPRECIOTD]
	/*21*/,[TRACONTENEDOR],[DOW_MODAL],[DOW_FSHIPMENTCONS],[DOW_HSHIPMENTCONS],[DOW_COMEN1],[DOW_COMEN2]
	/*22*/,[DOW_MED1],[DOW_MED2],[TRAINCI1],[TRAINCI2],[RELFACNO],[FIRMAELECPREVIO]
	/*23*/,[TRADESCTRAFICO],[MANIFIESTO],[PERSONAFIRMA],[FCARGADOGEN],[TRADESCARGA],[TRAHTTRANSBORDO]
	/*24*/,[TRAHERRTIGUIA],[TRAHPR],[HTTRANSBORDO],[HERRTIGUIA],[HPR],[TRACHOFERLC]
	/*25*/,[TRATRANSFERLC],[TRADESADUANADO],[TRAFEMATRACK],[TRAFLLEGADAGANCHAR],[TRAHLLEGADAGANCHAR],[TRAFROJOMEX]
	/*26*/,[TRAHROJOMEX],[TRAFVERDEMEX],[TRAHVERDEMEX],[TRAFROJOAME],[TRAHROJOAME],[TRAFVERDEAME]
	--/*27*/,[TRAHVERDEAME],[TRAFENTREGAFINAL],[TRAHENTREGAFINAL],[TRAQUIENRECIBE],[TRASELLOS],[traValor]
	/*27*/,[TRAHVERDEAME],[TRAFENTREGAFINAL],[TRAHENTREGAFINAL],[TRAQUIENRECIBE],NULL,[traValor]
	/*28*/,[TRADESTINA],[TRAFECHAOFICINA],[TRAFECHAFRONTERA],[TRAHORAOFICINA],[TRAHORAFRONTERA],[TRAHORAENTREGA]
	/*29*/,[TRADESPACHO],[TRASTATUSMANUAL],[TRAFAVISO],[TRAHAVISO],[TRAFPREFILE],[TRAHPREFILE]
	/*30*/,[BROKENSEAL],[NEWSEAL],[SEALCOLOR],[ARRIVALDATECUSTOM],[TRAENTMANI],[TRARECMANI]
	/*31*/,[TRAAAA],[MUESTREADO],[PRODMUES],[DETENIDO],[OBSPUNTO],[FDARELEASE]
	/*32*/,[FDARELEASEH],[ENVIOBL],[FSFFEDEST],[HSFFEDEST],[FLLDEST],[HLLDEST]
	/*33*/,[TRADATESLP],[TRADATENOTI],[TRATRANSFER],[ARRIVALTIMECUSTOM],[SEALRECIEVEDBY],[LDOFWHSE]
	/*34*/,[TRATIPOCONTENEDOR],[LDOHWHSE],[sealwasbroken],[TRAFSALPLA],[TRAHSALPLA],[plantaemb]
	/*35*/,[TRAHORARECMANI],[PIDI],[TRARECHMANI],[TRAENTHMANI],[NO_ENTRY],[PLACAS]
	/*36*/,[ESTADO_CAJA],[SERIE],[REFCLIENTE],[INBOND],[TRASELLONUEVO],[FACTURA]
	/*37*/,[OFECHASAL],[OHORASAL],[OFECHA_A26],[OHORA_A26],[OFECHA_OFICINA],[OHORA_OFICINA]
	/*38*/,[OPERADOR],[UNIDAD],[SCAC_CODE],[TRASELLOS_TRACKING],[SUCURSAL_TRACKING],[CITA_FECHACARGA_TRACKING]
	/*39*/,[CITA_HORACARGA_TRACKING],[PISTAS],[DOBLE_OPERADOR],[PAIS_CAJA],[TRADESTINO],[CONSM3]
	FROM TRAFICO
	WHERE trareferencia=@REFORG AND PREF=@PREF;

	-- BULTOS
	INSERT INTO [tblBultos]
	([bulref],[bulControl],[bulmarcas],[bulcanti],[buldimension]
	,[bulnumero],[bulclase],[ULTIMA_MOD],[PREF],[CLAVEBULTO])
	SELECT
	@Referencia,@Referencia,[bulmarcas],[bulcanti],[buldimension]
	,[bulnumero],[bulclase],CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),[PREF],[CLAVEBULTO]
	FROM [tblBultos] WHERE [bulControl]=@REFORG AND PREF=@PREF

	-- BLADING
	INSERT INTO BLADING (REFERENCIA,BODBNO,VALOR,FACTURA,PREF)
	SELECT @Referencia,BODBNO,VALOR,FACTURA,PREF FROM BLADING WHERE REFERENCIA=@REFORG
	AND PREF=@PREF

	-- MASCAJAS
	INSERT INTO MASCAJAS(REFERENCIA,BODCAJA,PREF)
	SELECT @Referencia,BODCAJA,PREF FROM MASCAJAS WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- DESTINO
	IF (SELECT CPDB FROM SEGURIDAD WHERE PREF=@PREF)=1
	BEGIN
		INSERT INTO DESTINO(REFERENCIA,BODDESTINO,PREF)
		SELECT @Referencia,BODDESTINO,PREF FROM DESTINO WHERE REFERENCIA=@REFORG AND PREF=@PREF
	END

	-- PARTES A DETALLE
	IF (SELECT CPD FROM SEGURIDAD WHERE PREF=@PREF)=1
	BEGIN
		INSERT INTO PARTES_DET(
			REFERENCIA,ORDEN,PARTE,DESC1,PAIS,UNIDAD_TEXT,UNIDAD_NUM,CANTIDAD,PUNITARIO,
			PESO,PESO_KGS,TOTAL,USADA,FECHA,FACTURA,FECHAFAC,RECIVO,DMT,PREF,PESOBLBS,PESOBKGS,BULTOS,
			BULTOS_DESC,PEDIDO,CANTIDADREC,CANTIDADDAN,CANTIDADSOB,OBS)
		SELECT
			@Referencia,ORDEN,PARTE,DESC1,PAIS,UNIDAD_TEXT,UNIDAD_NUM,CANTIDAD,PUNITARIO,
			PESO,PESO_KGS,TOTAL,USADA,CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),FACTURA,FECHAFAC,RECIVO,DMT,PREF,PESOBLBS,PESOBKGS,BULTOS,
			BULTOS_DESC , pedido, CANTIDADREC, CANTIDADDAN, CANTIDADSOB,OBS
		FROM PARTES_DET WHERE REFERENCIA=@REFORG AND PREF=@PREF
	END

	-- FACTURAS
	INSERT INTO [tblFactgen]
		([facgnofac],[facgref],[facgrefc],[facgfefac],[facgvalor],[facgmoneda]
		,[facgPais],[facgprov],[facgcli],[facgferec],[facgtotpar],[facgcontenido]
		,[facgMetRec],[facgfletes],[facgSeguros],[facgOtros],[facgValorMerc],[facgBandera]
		,[facgClasificada],[facgsubdivision],[facgUsuario],[FACGPESOBRUTO],[FACGPESONETO]
		,[FACGOBS],[TLC],[FACGENTIDAD],[FACGINCOTERM],[VIN],[FACGPAISV]
		,[FACGHORAREC],[ULTIMA_MOD],[FECHAREGISTRO],[SHIPID],[SALESORDER],[ACCOUNTNO]
		,[BODADUANA],[FACGHRECIB],[FACGHORAENT],[FACGHORASAL],[FACGHORAFINAL],[FACGRESPONSABLE]
		,[FACGOBS2],[FACGFLETE],[FACGFRECIB],[FACGFENTREGA],[FACGFSAL],[FACGFFINAL]
		,[FACBL],[USUARIO_ID],[PREF],[SUCURSAL],[FAC_ORDEN],[FACGFECHASUB],[FACTURACORRECTA]
		,[FACGPLANTA],[EDETYEM],[TRAPARTETD],[TRACANTIDADTD],[TRAPRECIOTD],[CERTIFICADODEANALISIS]
		,[OS],[BAANORDER],[WO],[SOA],[ME],[SO],[BO]
		,[FACGPVEHICULO],[FACGPCANDADOS],[FACGCONFACT],[FACGCANCOMSU],[FECHARECMERC]
		,[FECHARECIBIDOIFFI],[FECHARMA],[FECHAPNP],[BILL],[HORARECMERC],[RECIBIDOIFFI]
		,[RMA],[PNP],[CREDITO],[FACGDESCUENTOS],[FACGCLIENTE2],[FACGMET]
		,[CRUZADA],[FACMPF],[FACTORMONEXT],[EMBALAJES],[FACTURA_ID2],[FACGREMESANO]
		,[PEDIMENTO_CON],[REGIMEN_CON],[SELLOS_CON],[VEH_TIPO],[CAJA_CON],[FIRMA_CON]
		,[FACGHM],[FACGNOTA],[BL],[FACGMATPEG],[FACGDATESHIP],[FACGBH6],[FACGBH9]
		,[FACGBOH6],[FACGBOH9],[FACGBEAMS],[FACGPROFAC],[FACGADUANA],[FACGPEDIMENTO]
		,[FACGCANDADOS],[FACGVEHICULO],[FACGPESO],[FACGBULTOS],[piezasnuevas]
		,[FACGCANTI],[CRUCESM3],[FACGFCRUCE],[FACGHCRUCE],[FACGHREC],[FACGFEENV]
		,[FACGNUMPED],[FACGSUCURSAL],[FACGTOTGUIAS],[FACGNUMIDU],[FacturaSubdividida])
	SELECT
		[facgnofac],@Referencia,[facgrefc],[facgfefac],[facgvalor],[facgmoneda]
		,[facgPais],[facgprov],[facgcli],[facgferec],[facgtotpar],[facgcontenido]
		,[facgMetRec],[facgfletes],[facgSeguros],[facgOtros],[facgValorMerc],[facgBandera]
		,[facgClasificada],[facgsubdivision],[facgUsuario],[FACGPESOBRUTO],[FACGPESONETO]
		,[FACGOBS],[TLC],[FACGENTIDAD],[FACGINCOTERM],[VIN],[FACGPAISV]
		,[FACGHORAREC],CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),[FECHAREGISTRO],[SHIPID],[SALESORDER],[ACCOUNTNO]
		,[BODADUANA],[FACGHRECIB],[FACGHORAENT],[FACGHORASAL],[FACGHORAFINAL],[FACGRESPONSABLE]
		,[FACGOBS2],[FACGFLETE],[FACGFRECIB],[FACGFENTREGA],[FACGFSAL],[FACGFFINAL]
		,[FACBL],[USUARIO_ID],[PREF],[SUCURSAL],[FAC_ORDEN],[FACGFECHASUB],[FACTURACORRECTA]
		,[FACGPLANTA],[EDETYEM],[TRAPARTETD],[TRACANTIDADTD],[TRAPRECIOTD],[CERTIFICADODEANALISIS]
		,[OS],[BAANORDER],[WO],[SOA],[ME],[SO],[BO]
		,[FACGPVEHICULO],[FACGPCANDADOS],[FACGCONFACT],[FACGCANCOMSU],[FECHARECMERC]
		,[FECHARECIBIDOIFFI],[FECHARMA],[FECHAPNP],[BILL],[HORARECMERC],[RECIBIDOIFFI]
		,[RMA],[PNP],[CREDITO],[FACGDESCUENTOS],[FACGCLIENTE2],[FACGMET]
		,[CRUZADA],[FACMPF],[FACTORMONEXT],[EMBALAJES],[FACTURA_ID2],[FACGREMESANO]
		,[PEDIMENTO_CON],[REGIMEN_CON],[SELLOS_CON],[VEH_TIPO],[CAJA_CON],[FIRMA_CON]
		,[FACGHM],[FACGNOTA],[BL],[FACGMATPEG],[FACGDATESHIP],[FACGBH6],[FACGBH9]
		,[FACGBOH6],[FACGBOH9],[FACGBEAMS],[FACGPROFAC],[FACGADUANA],[FACGPEDIMENTO]
		,[FACGCANDADOS],[FACGVEHICULO],[FACGPESO],[FACGBULTOS],[piezasnuevas]
		,[FACGCANTI],[CRUCESM3],[FACGFCRUCE],[FACGHCRUCE],[FACGHREC],[FACGFEENV]
		,[FACGNUMPED],[FACGSUCURSAL],[FACGTOTGUIAS],[FACGNUMIDU],[FacturaSubdividida]
	FROM [tblFactgen]
	WHERE FACGREF=@REFORG AND PREF=@PREF
	ORDER BY [factura_id]

	/*Ing. Daniel Sanchez 22-agosto-2011*/
	/* ********************************** */
	DECLARE @FACIDOLD AS BIGINT

	SELECT *
	INTO #FACTURASORIGINALES
	FROM dbo.tblFactgen
	WHERE facgref=@REFORG AND PREF=@PREF
	/* ********************************** */

	SELECT *
	INTO #FACTURAS
	FROM dbo.tblFactgen
	WHERE facgref=@Referencia AND PREF=@PREF

	SELECT	@FACIDNEW = MIN(factura_id)
	FROM	#FACTURAS

	/*Ing. Daniel Sanchez 22-agosto-2011*/
	/* ********************************** */
	SELECT	@FACIDOLD = MIN(factura_id)
	FROM	#FACTURASORIGINALES
	/* ********************************** */

	SELECT	@FACNUMTEMP = MIN(facgnofac)
	FROM	#FACTURAS
	WHERE	Factura_id=@FACIDNEW

	WHILE @FACIDNEW IS NOT NULL
	  BEGIN
		 --SELECT @FACIDNEW
		 -- CLASIFICACION
			INSERT INTO [tblClasifica]
				([Factura],[Factura_id],[Fecha],[REFERENCIA],[Renglon],[DescRen]
				,[NumFraccion],[OBFRAC],[DescFra],[PaisOrigen],[TLC],[TLCTexto]
				,[UA],[CANTFAC],[UMFAC],[UMUMF],[UniMedFac],[UniMedTar],[Cantidad]
				,[CantTar],[PreUnitario],[Total],[IVA],[ADV],[ISAN],[IEPS]
				,[Pesolbs],[PesoKgs],[Usuario],[CC],[PorcCC],[CLAVE1],[NUMCLAVE1]
				,[FIRMCLAVE1],[CLAVE2],[NUMCLAVE2],[FIRMCLAVE2],[CLAVE3],[NUMCLAVE3]
				,[FIRMCLAVE3],[PROSEC],[ENTIDAD],[EDESTINO],[ECOMP],[EVEND]
				,[VIN],[PV],[NOTAS],[REQ],[PEDIDO],[PARTIDAPEDIDO],[PLANTA]
				,[ULTIMA_MOD],[INDUSTRIA],[NUMPARTE],[HORA],[FRAAME],[DESCFRAAME]
				,[VPR],[FACGFRECIB],[FACGFENTREGA],[FACGFSAL],[FACGFFINAL],[RENGLONFIJO]
				,[PARCIAL],[NUMSERIE],[PREF],[CLAVE1A],[CLAVE4],[NUMCLAVE4]
				,[FIRMCLAVE4],[CLAVE5],[NUMCLAVE5],[FIRMCLAVE5],[FALTANTES],[MA]
				,[USUARIO_MOD],[REQ2],[PARTNUMPROV],[METVAL],[PERMISO],[FOLIOINTSAN]
				,[SKU],[CANTIDADDAN],[BOXNUMBER],[CANTIDADSOB],[FIRMA],[FIRMAVENCE]
				,[AZUCAR],[OTROS_TLC],[TIPO_TLC],[BPESOKGS],[BPESOLBS],[FACTURA_ID2]
				,[FP],[REFERENCIA_PED],[SECUENCIA_PED],[SECUENCIA_CON],[FP_IVA]
				,[ORDENTRABAJO],[NUMPARCLI],[LOTE],[NBSRP],[UM_FE],[VALIDO]
				,[BLANKET],[CARTONES])
			SELECT
				[Factura],@FACIDNEW,[Fecha],@Referencia,[Renglon],[DescRen]
				,[NumFraccion],[OBFRAC],[DescFra],[PaisOrigen],[TLC],[TLCTexto]
				,[UA],[CANTFAC],[UMFAC],[UMUMF],[UniMedFac],[UniMedTar],[Cantidad]
				,[CantTar],[PreUnitario],[Total],[IVA],[ADV],[ISAN],[IEPS]
				,[Pesolbs],[PesoKgs],[Usuario],[CC],[PorcCC],[CLAVE1],[NUMCLAVE1]
				,[FIRMCLAVE1],[CLAVE2],[NUMCLAVE2],[FIRMCLAVE2],[CLAVE3],[NUMCLAVE3]
				,[FIRMCLAVE3],[PROSEC],[ENTIDAD],[EDESTINO],[ECOMP],[EVEND]
				,[VIN],[PV],[NOTAS],[REQ],[PEDIDO],[PARTIDAPEDIDO],[PLANTA]
				,CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),[INDUSTRIA],[NUMPARTE],[HORA],[FRAAME],[DESCFRAAME]
				,[VPR],[FACGFRECIB],[FACGFENTREGA],[FACGFSAL],[FACGFFINAL],[RENGLONFIJO]
				,[PARCIAL],[NUMSERIE],[PREF],[CLAVE1A],[CLAVE4],[NUMCLAVE4]
				,[FIRMCLAVE4],[CLAVE5],[NUMCLAVE5],[FIRMCLAVE5],[FALTANTES],[MA]
				,[USUARIO_MOD],[REQ2],[PARTNUMPROV],[METVAL],[PERMISO],[FOLIOINTSAN]
				,[SKU],[CANTIDADDAN],[BOXNUMBER],[CANTIDADSOB],[FIRMA],[FIRMAVENCE]
				,[AZUCAR],[OTROS_TLC],[TIPO_TLC],[BPESOKGS],[BPESOLBS],[FACTURA_ID2]
				,[FP],[REFERENCIA_PED],[SECUENCIA_PED],[SECUENCIA_CON],[FP_IVA]
				,[ORDENTRABAJO],[NUMPARCLI],[LOTE],[NBSRP],[UM_FE],[VALIDO]
				,[BLANKET],[CARTONES]
			FROM [tblClasifica]
			--WHERE REFERENCIA=@REFORG AND Factura=@FACNUMTEMP AND PREF=@PREF
			/*Ing. Daniel Sanchez 22-agosto-2011*/
			/* ********************************** */
			WHERE REFERENCIA=@REFORG AND PREF=@PREF And FACTURA_ID=@FACIDOLD
			/* ********************************** */

		 SELECT	@FACIDNEW = MIN(factura_id)
		 FROM	#FACTURAS
		 WHERE	factura_id > @FACIDNEW

		/*Ing. Daniel Sanchez 22-agosto-2011*/
		/* ********************************** */
		 SELECT	@FACIDOLD = MIN(factura_id)
		 FROM	#FACTURASORIGINALES
		 WHERE	factura_id > @FACIDOLD
		/* ********************************** */

		 SELECT	@FACNUMTEMP = MIN(facgnofac)
		 FROM	#FACTURAS
		 WHERE	Factura_id=@FACIDNEW
	  END

	DROP TABLE #FACTURAS

	-- PEDIDOS
	INSERT INTO [tblPedidoFac]
	([NumFac],[NumPedido],[Factura_id],[REFERENCIA],[REQUISICION],[ULTIMA_MOD],[PREF])
	SELECT
	[NumFac],[NumPedido],[Factura_id],@Referencia,[REQUISICION],CAST(FLOOR(CAST(GETDATE() AS FLOAT))AS DATETIME),[PREF]
	FROM [tblPedidoFac]
	WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- GASTOS
	INSERT INTO [GOTROS]
	([REFERENCIA],[Gasto_id],[GASTO],[VALOR],[CSIN],[SESUMA]
	,[GASTOINC],[PRODUCTO],[CAJA],[PLATAFORMA],[PLAZUELA],[SHIPMENT]
	,[FECHA],[OTHERS3],[OTHERS4],[PREF],[PLATAFORMA_ID],[CHEQUE],[USUARIO])
	SELECT
	@Referencia,[Gasto_id],[GASTO],[VALOR],[CSIN],[SESUMA]
	,[GASTOINC],[PRODUCTO],[CAJA],[PLATAFORMA],[PLAZUELA],[SHIPMENT]
	,[FECHA],[OTHERS3],[OTHERS4],[PREF],[PLATAFORMA_ID],[CHEQUE],[USUARIO]
	FROM [GOTROS]
	WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- NOTA GENERAL
	INSERT INTO [tblNotaRevGen]
		([Referencia],[fecha],[Solicitud],[FechaSol],[Certificado],[FechaCert],[Pedimento]
		,[FacturasFechas],[Pedidos],[ImpExp],[Cliente_id],[Proveedor_id],[Observaciones]
		,[Instrucciones],[Usuario_id],[HoraActual],[PesoTotalKgs],[PesoNetoKgs],[TipoCambioCont]
		,[TipoCambioLibre],[ValorComMe],[ValorComDlls],[ValorComMex],[ValorFacturaMe]
		,[ValorFacturaDlls],[ValorFacturaMex],[ValorNormalMex],[FactorMonExt],[FactorAct]
		,[FactorAjuste],[FletesIncDlls],[SegurosIncDlls],[OtrosIncDlls],[EmbalagesIncDlls]
		,[TotalIncDlls],[TotalIncMex],[Ded1Dlls],[Ded2Dlls],[TotalDedDlls],[TotalDedMex]
		,[ServCompMex],[ServComp_porc],[HonorariosMex],[OtrosMex],[IVAMex],[TotalcMex]
		,[EstibaAmDlls],[EstibaAmMex],[FletesAmDlls],[FletesAmMex],[CODAmDlls],[CODAmMex]
		,[OtrosAmDlls],[OtrosAmMex],[TotalCAmDlls],[TotalCAmMex],[CantidadBod],[TotalADV]
		,[TotalDTA],[TotalIVA],[TotalISAN],[TotalIEPS],[TotImp],[TotAnticipo],[TNExp]
		,[TNImp],[Producer],[DirProducer],[TNProducer],[Name],[Date],[FromDate],[ToDate]
		,[Company],[Title],[Tel],[Fax],[CLAVEPED],[TIPO_REG],[PEDGEN],[ValorTotalCC]
		,[OBSSHIP],[ISR],[IVARETENIDO],[CONSOLIDADOS],[OBSERVACIONSOL],[DESCBULTOS]
		,[ADUANA],[FRONINT],[OBS1],[OBS2],[OBS3],[LEYENDA],[SITCI],[GSITCI],[ANTICIPO_SOL]
		,[PCAAAREM],[ULTIMA_MOD],[POSTFIJO],[PORHON],[RELFACNO],[REMESANO],[OBSBIN]
		,[TOTINSPECCION],[PREF],[PORMINIMO],[FLETESDESC],[SEGUROSDESC],[BANDERAREV]
		,[TOTALFACTURAS],[FLETESMEX],[CONTENEDORES],[GLOSADO],[REVISO],[LAVOCONTENEDOR]
		,[NOTAREVISO],[IDEN_GLOBAL],[PEDPAR2VALOR],[PEDPAR2],[MEMO1],[MEMO2],[NUE]
		,[DESTINO_FINAL],[FINPC],[FRECARGO],[INPC_VIGENTE],[INPC_ANTERIOR],[RECARGO],[ECI]
		,[ADICFLETESINCDLLS],[ADICSEGUROSINCDLLS],[ADICOTROSINCDLLS])
	SELECT
		 @Referencia,[fecha],[Solicitud],[FechaSol],[Certificado],[FechaCert]
		 ,@Pedimento--[Pedimento]
		,[FacturasFechas],[Pedidos],@IMPEXP,[Cliente_id],[Proveedor_id],[Observaciones]
		,[Instrucciones],[Usuario_id],[HoraActual],[PesoTotalKgs],[PesoNetoKgs],[TipoCambioCont]
		,[TipoCambioLibre],[ValorComMe],[ValorComDlls],[ValorComMex],[ValorFacturaMe]
		,[ValorFacturaDlls],[ValorFacturaMex],[ValorNormalMex],[FactorMonExt],[FactorAct]
		,[FactorAjuste],[FletesIncDlls],[SegurosIncDlls],[OtrosIncDlls],[EmbalagesIncDlls]
		,[TotalIncDlls],[TotalIncMex],[Ded1Dlls],[Ded2Dlls],[TotalDedDlls],[TotalDedMex]
		,[ServCompMex],[ServComp_porc],[HonorariosMex],[OtrosMex],[IVAMex],[TotalcMex]
		,[EstibaAmDlls],[EstibaAmMex],[FletesAmDlls],[FletesAmMex],[CODAmDlls],[CODAmMex]
		,[OtrosAmDlls],[OtrosAmMex],[TotalCAmDlls],[TotalCAmMex],[CantidadBod],[TotalADV]
		,[TotalDTA],[TotalIVA],[TotalISAN],[TotalIEPS],[TotImp],[TotAnticipo],[TNExp]
		,[TNImp],[Producer],[DirProducer],[TNProducer],[Name],[Date],[FromDate],[ToDate]
		,[Company],[Title],[Tel],[Fax],[CLAVEPED],[TIPO_REG],[PEDGEN],[ValorTotalCC]
		,[OBSSHIP],[ISR],[IVARETENIDO],[CONSOLIDADOS],[OBSERVACIONSOL],[DESCBULTOS]
		,[ADUANA],[FRONINT],[OBS1],[OBS2],[OBS3],[LEYENDA],[SITCI],[GSITCI],[ANTICIPO_SOL]
		,[PCAAAREM],[ULTIMA_MOD],[POSTFIJO],[PORHON],[RELFACNO],[REMESANO],[OBSBIN]
		,[TOTINSPECCION],[PREF],[PORMINIMO],[FLETESDESC],[SEGUROSDESC],[BANDERAREV]
		,[TOTALFACTURAS],[FLETESMEX],[CONTENEDORES],[GLOSADO],[REVISO],[LAVOCONTENEDOR]
		,[NOTAREVISO],[IDEN_GLOBAL],[PEDPAR2VALOR],[PEDPAR2],[MEMO1],[MEMO2],[NUE]
		,[DESTINO_FINAL],[FINPC],[FRECARGO],[INPC_VIGENTE],[INPC_ANTERIOR],[RECARGO],[ECI]
		,[ADICFLETESINCDLLS],[ADICSEGUROSINCDLLS],[ADICOTROSINCDLLS]
	FROM [tblNotaRevGen]
	WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- NOTA DETALLE
	INSERT INTO [tblNotaRevDet]
		([Fraccion],[SubFra],[Renglon],[DescRen],[Referencia],[DescFrac]
		,[OBFRAC],[PesoKgs],[PaisOrigen],[CantComMe],[CantComDlls],[CantComMex]
		,[UniMedFac],[Cantidad],[UniMedTar],[CantTar],[ADVporcentaje],[IVAporcentaje]
		,[ISANporcentaje],[IEPSporcentaje],[ADV],[IVA],[ISAN],[IEPS]
		,[DTA],[VIVA],[TLC],[Anexo],[ValorFraccion],[ValorAduana],[NORMA]
		,[CC],[PorcCC],[ValorCC],[NUMCLAVE1],[FIRMCLAVE1],[CLAVE2],[NUMCLAVE2]
		,[FIRMCLAVE2],[CLAVE3],[NUMCLAVE3],[FIRMCLAVE3],[ORDEN],[ORDENB],[PROSEC]
		,[ENTIDAD],[EDESTINO],[ECOMP],[EVEND],[VIN],[PARTIDA_ID],[PV],[NOTAS]
		,[INDUSTRIA],[FRAAME],[DESCFRAAME],[RENGLONBIN],[CLAVE1],[INSPECCION]
		,[PREF],[REQ],[MA],[IDENTIFICADORES],[PERMISOS],[PROVEEDOR_ID],[CCE]
		,[METVAL],[PARTES],[PERMISO],[FOLIOINTSAN],[PLANTA],[FACTURA]
		,[FIRMA],[FP],[RECARGO],[FP_IVA],[AZUCAR],[NBSRP])
	SELECT
		[Fraccion],[SubFra],[Renglon],[DescRen],@Referencia,[DescFrac]
		,[OBFRAC],[PesoKgs],[PaisOrigen],[CantComMe],[CantComDlls],[CantComMex]
		,[UniMedFac],[Cantidad],[UniMedTar],[CantTar],[ADVporcentaje],[IVAporcentaje]
		,[ISANporcentaje],[IEPSporcentaje],[ADV],[IVA],[ISAN],[IEPS]
		,[DTA],[VIVA],[TLC],[Anexo],[ValorFraccion],[ValorAduana],[NORMA]
		,[CC],[PorcCC],[ValorCC],[NUMCLAVE1],[FIRMCLAVE1],[CLAVE2],[NUMCLAVE2]
		,[FIRMCLAVE2],[CLAVE3],[NUMCLAVE3],[FIRMCLAVE3],[ORDEN],[ORDENB],[PROSEC]
		,[ENTIDAD],[EDESTINO],[ECOMP],[EVEND],[VIN],[PARTIDA_ID],[PV],[NOTAS]
		,[INDUSTRIA],[FRAAME],[DESCFRAAME],[RENGLONBIN],[CLAVE1],[INSPECCION]
		,[PREF],[REQ],[MA],[IDENTIFICADORES],[PERMISOS],[PROVEEDOR_ID],[CCE]
		,[METVAL],[PARTES],[PERMISO],[FOLIOINTSAN],[PLANTA],[FACTURA]
		,[FIRMA],[FP],[RECARGO],[FP_IVA],[AZUCAR],[NBSRP]
	FROM [tblNotaRevDet]
	WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- NOTA DETALLE SHIPPER
	INSERT INTO [tblnotarevdets]
		([REFERENCIA],[SUBREF],[CLIENTE_ID],[PROVEEDOR_ID],[PARTIDA_ID]
		,[FRACCION],[DESCFRAC],[CANTIDAD],[PESOKGS],[CANTCOMDLLS],[PAISORIGEN]
		,[UNIMEDFAC],[CANTTAR],[PREF],[TLC])
	SELECT
		@Referencia,[SUBREF],[CLIENTE_ID],[PROVEEDOR_ID],[PARTIDA_ID]
		,[FRACCION],[DESCFRAC],[CANTIDAD],[PESOKGS],[CANTCOMDLLS],[PAISORIGEN]
		,[UNIMEDFAC],[CANTTAR],[PREF],[TLC]
	FROM [tblnotarevdets]
	WHERE REFERENCIA=@REFORG AND PREF=@PREF

	-- Insert IDENTIFICADORES
	print 'IDENTIFICADORES'

	INSERT INTO [IDENTIFICADORES]
			   ([PARTIDA_ID] ,[REFERENCIA] ,[FRACCION] ,[CLAVE],[IDENTIFICADOR]
			   ,[IDENTIFICADOR2] ,[PREF] ,[ORDEN] ,[IDENTIFICADOR3])
	   Select [PARTIDA_ID] ,@Referencia ,[FRACCION] ,[CLAVE],[IDENTIFICADOR]
			   ,[IDENTIFICADOR2] ,[PREF] ,[ORDEN] ,[IDENTIFICADOR3]
	   from identificadores where referencia = @REFORG and pref = @PREF and CLAVE <> 'ED'


	-- Insert PERMISOS
	print 'PERMISOP'
	INSERT INTO [PERMISOP]
			   ([PARTIDA_ID] ,[REFERENCIA] ,[FRACCION] ,[CLAVE] ,[FIRMA]
			   ,[PERMISO] ,[VALDOL] ,[CANUMT],[ORDEN] ,[PREF])
		Select [PARTIDA_ID] ,[REFERENCIA] ,[FRACCION] ,[CLAVE] ,[FIRMA]
			   ,[PERMISO] ,[VALDOL] ,[CANUMT],[ORDEN] ,[PREF]
		  from permisop where referencia = @REFORG and pref = @PREF

	-- Inserta en TABLA CONSOLIDADO
	print 'Insert CONSOLIDADO'

	INSERT INTO consolidado (referenciap, referenciac, maquila,prefijo,traficomaster,pref)
	select @Referencia as referenciap, referenciac,maquila,prefijo,traficomaster,pref
	 from consolidado where referenciap=@REFORG AND PREF=@PREF

	update consolidado set referenciac=@Referencia where referenciap=@Referencia and referenciac=@REFORG and pref=@PREF

	-- INSERTA Mascontenedores
	insert into mascontenedoresref (numrel,caja,tipo_cont,orden,pref)
	select @Referencia as numrel,caja,tipo_cont,orden,pref
	from mascontenedoresref where numrel=@REFORG AND PREF=@PREF

	-- Insertar en PF_COMPENSACIONES
	print 'PF_COMPENSACIONES'
	INSERT INTO PF_COMPENSACIONES (referencia,pref,patente_orig,pedimento_orig,
		aduana_sec_orig,fecha_op_orig,cve_gravamen,	importe)
	SELECT @Referencia,pref,patente_orig,pedimento_orig,aduana_sec_orig,fecha_op_orig,cve_gravamen,	importe
	FROM PF_COMPENSACIONES where referencia = @REFORG and pref=@PREF

	-- Insertar PF_CTA_ADUANERA_GEN
	print 'PF_CTA_ADUANERA_GEN'
	INSERT INTO PF_CTA_ADUANERA_GEN (referencia,pref,tipo_cuenta,cve_garantia,emisora,
		  num_contrato ,folio_constancia,total_dep,fecha_constancia)
	SELECT @Referencia,pref, tipo_cuenta,cve_garantia,emisora,
	   num_contrato ,folio_constancia,total_dep,fecha_constancia
	FROM PF_CTA_ADUANERA_GEN where referencia = @REFORG and pref=@PREF

	-- Insertar PF_CTA_ADUANERA_PARTIDA
	print 'PF_CTA_ADUANERA_PARTIDA'

	INSERT INTO PF_CTA_ADUANERA_PARTIDA
	 (referencia ,pref ,fraccion ,subfra,orden,ordenb,cve_garantia ,emisora,
	   num_cuenta ,folio_constancia ,total_dep,fecha_constancia,precio_estimado,
			   CANT_UM_est ,partida_id)
	SELECT @Referencia,pref ,fraccion ,subfra,orden,ordenb,cve_garantia ,emisora,
	   num_cuenta ,folio_constancia ,total_dep,fecha_constancia,precio_estimado,
			   CANT_UM_est ,partida_id
	FROM PF_CTA_ADUANERA_PARTIDA where referencia = @REFORG and pref =@PREF

	-- Insertar PF_DATOS_PEDIM
	print 'PF_DATOS_PEDIM'
	INSERT INTO PF_DATOS_PEDIM (referencia,pref,medio_entrada,medio_arribo,medio_salida
			   ,aduana_sec,aduana_sec_despacho,val_seguros ,id_fiscal_dest ,nombre_dest
			   ,dom_dest,referencia_pedim,patente,observaciones,rfc_factura,id_reg_agente
			   ,num_veh,clave_ped_R1 ,marcas_numeros)
	SELECT @Referencia ,pref,medio_entrada,medio_arribo,medio_salida
			   ,aduana_sec,aduana_sec_despacho,val_seguros ,id_fiscal_dest ,nombre_dest
			   ,dom_dest,@Referencia,left(@Pedimento,4),observaciones,rfc_factura,id_reg_agente
			   ,num_veh,clave_ped_R1 ,marcas_numeros
	FROM PF_DATOS_PEDIM where referencia = @REFORG and pref = @PREF

	-- Insertar PF_DATOS_TRANSPORTE
	print 'PF_DATOS_TRANSPORTE'

	INSERT INTO PF_DATOS_TRANSPORTE (referencia,pref ,identificacion ,pais
			  ,nombre_trans,rfc ,curp,domicilio ,candados)
	SELECT @Referencia, pref ,identificacion ,pais
			  ,nombre_trans,rfc ,curp,domicilio ,candados
	FROM PF_DATOS_TRANSPORTE where referencia = @REFORG and pref = @PREF

	-- Insertar PF_DESCARGOS
	print 'PF_DESCARGOS'
	INSERT INTO PF_DESCARGOS (referencia,pref ,patente_orig
			   ,pedimento_orig ,aduana_sec_orig  ,cve_pedim_orig
			   ,fecha_op_orig ,fraccion_orig ,cve_unidad_orig
			   ,cant_descargar)
	SELECT @Referencia ,pref ,patente_orig ,pedimento_orig ,aduana_sec_orig  ,cve_pedim_orig
			   ,fecha_op_orig ,fraccion_orig ,cve_unidad_orig ,cant_descargar
	FROM PF_DESCARGOS where referencia = @REFORG and pref = @PREF

	-- Insertar PF_GUIAS_PEDIMENTO
	print 'PF_GUIAS_PEDIMENTO'
	INSERT INTO [PF_GUIAS_PEDIMENTO] ([referencia] ,[pref] ,[num_guia] ,[ID] ,[rango_envio_I] ,[rango_envio_f])
	SELECT      @Referencia ,pref ,num_guia ,ID ,rango_envio_I ,rango_envio_f
	FROM PF_GUIAS_PEDIMENTO where referencia =@REFORG and pref = @PREF

	-- Insertar PF_FECHAS_PEDIMENTO
	print 'PF_FECHAS_PEDIMENTO'
	INSERT INTO PF_FECHAS_PEDIMENTO (referencia ,pref ,tipo_fecha ,fecha )
	SELECT @Referencia,pref,tipo_fecha,fecha
	FROM PF_FECHAS_PEDIMENTO where referencia=@REFORG and pref=@PREF

	-- Insertar PF_PAGO_VIRTUAL
	print 'PF_PAGO_VIRTUAL'
	INSERT INTO PF_PAGO_VIRTUAL (referencia ,pref ,forma_pago ,institucion ,documento
			   ,fecha_doc ,importe ,saldo ,importe_pagar)
	SELECT @Referencia,pref,forma_pago,institucion ,documento
			   ,fecha_doc ,importe ,saldo ,importe_pagar
	FROM PF_PAGO_VIRTUAL where referencia=@REFORG and pref=@PREF

	-- Insertar PF_PARTIDAS_MERCANCIAS
	print 'PF_PARTIDAS_MERCANCIAS'

	INSERT INTO PF_PARTIDAS_MERCANCIAS (referencia ,pref ,fraccion ,subfra ,orden
			   ,ordenb ,renglon ,marca ,modelo  ,vin_num_serie ,kilometraje
			   ,partida_id)
	SELECT @Referencia  ,pref ,fraccion ,subfra ,orden
			   ,ordenb ,renglon ,marca ,modelo  ,vin_num_serie ,kilometraje
			   ,partida_id
	FROM PF_PARTIDAS_MERCANCIAS where referencia=@REFORG and pref=@PREF

	--Insertar PF_PARTIDAS_PEDIMENTO
	print 'PF_PARTIDAS_PEDIMENTO'
	INSERT INTO [PF_PARTIDAS_PEDIMENTO] ([REFERENCIA] ,[PREF]  ,[FRACCION]   ,[SUBFRA]   ,[ORDEN]
			   ,[ORDENB] ,[PARTIDA_ID]  ,[VAL_AGREGADO] ,[MARCA] ,[MODELO] ,[OBSERVACIONES] ,[DESCFRACPF]
			   ,[METVALPF] ,[PV] ,[PAISORIGEN])
	SELECT @Referencia , pref ,FRACCION   ,SUBFRA   ,ORDEN
			   ,ORDENB ,PARTIDA_ID  ,VAL_AGREGADO ,MARCA ,MODELO ,OBSERVACIONES ,DESCFRACPF
			   ,METVALPF ,PV ,PAISORIGEN
	FROM PF_PARTIDAS_PEDIMENTO where referencia = @REFORG and pref=@PREF

	-- Insertar PF_PARTIDAS_PERMISO
	print 'PF_PARTIDAS_PERMISO'
	INSERT INTO [PF_PARTIDAS_PERMISO] ([referencia] ,[pref] ,[fraccion] ,[partida_id] ,[clave]
			   ,[firma] ,[permiso] ,[valdol]  ,[canumt])
	SELECT @Referencia , pref ,fraccion ,partida_id ,clave
			   ,firma ,permiso ,valdol  ,canumt
	FROM PF_PARTIDAS_PERMISO where referencia = @REFORG and pref=@PREF

	-- Insertar PF_PARTIDAS_TASAS_FP
	print 'PF_PARTIDAS_TASAS_FP'
	INSERT INTO PF_PARTIDAS_TASAS_FP (partida_id ,referencia  ,pref ,fraccion
			   ,subfra ,orden ,ordenb ,renglon ,CON ,TT ,FP ,importe
			   ,porcentaje ,tasa)
	SELECT partida_id ,@Referencia  ,pref ,fraccion
			   ,subfra ,orden ,ordenb ,renglon ,CON ,TT ,FP ,importe
			   ,porcentaje ,tasa
	FROM PF_PARTIDAS_TASAS_FP where referencia =@REFORG and pref=@PREF

	-- Insertar SAGARG
	print 'SAGARG'
	INSERT INTO SAGARg ([C031REFPED] ,[C031NUMFOL]  ,[C031CERFS] ,[D031FERTIF] ,[C031PLATIF] ,[C031PITEX]
			   ,[C031GUIA] ,[C031FLEJES] ,[C031TIPINS]  ,[C031CVEOISA]  ,[C031CVEOIS] ,[C031CLATRA],[C031IDETRA]
			   ,[C031NOMTRA] ,[C031CVEDES],[C031NOMDES] ,[C031DOMDES]  ,[C031NUMDES]  ,[C031COLDES],[C031CODDES]
			   ,[C031MUNDES] ,[C031EDODES],[C031CVEPA]  ,[C031LADADE]  ,[C031TELDES]  ,[C031CORNOR],[C031CORCEN]
			   ,[C031CORSUR] ,[C031CORITS] ,[C031CORPEN] ,[M031DESLEY] ,[FECHA_CAP]   ,[ULTIMA_MOD],[USUARIO_ID]
			   ,[PREF] ,[C031TIPMOD] ,[C031NUMCON] ,[N031MEDVET] ,[C031PRESENTA] ,[N031CANTPRE] ,[C031TIPPRE]
			   ,[C031FOLIOANT] ,[D031FECHAVAL] ,[C031ID_REG] ,[C031ID_EXPOR] ,[C031ID_IMPOR] ,[VALIDADOR]
			   ,[ASOCIACION])
	SELECT @Referencia ,C031NUMFOL  ,C031CERFS ,D031FERTIF ,C031PLATIF ,C031PITEX
			   ,C031GUIA ,C031FLEJES ,C031TIPINS  ,C031CVEOISA  ,C031CVEOIS ,C031CLATRA,C031IDETRA
			   ,C031NOMTRA ,C031CVEDES,C031NOMDES ,C031DOMDES  ,C031NUMDES  ,C031COLDES,C031CODDES
			   ,C031MUNDES ,C031EDODES,C031CVEPA  ,C031LADADE  ,C031TELDES  ,C031CORNOR,C031CORCEN
			   ,C031CORSUR ,C031CORITS ,C031CORPEN ,M031DESLEY ,FECHA_CAP   ,ULTIMA_MOD,USUARIO_ID
			   ,PREF ,C031TIPMOD ,C031NUMCON ,N031MEDVET ,C031PRESENTA ,N031CANTPRE ,C031TIPPRE
			   ,C031FOLIOANT ,D031FECHAVAL ,C031ID_REG,C031ID_EXPOR ,C031ID_IMPOR ,VALIDADOR
			   ,ASOCIACION
	FROM SAGARG where C031REFPED=@REFORG and pref=@PREF

	-- Insertar SAGARD
	print 'SAGARD'
	INSERT INTO [SAGARd] ([C032SECFRA],[C032REFPED] ,[C032FRAC],[C032DESCR],[C032USOPRO]
			   ,[F032CANUMT] ,[C032UNIUMT] ,[F032CANUMC] ,[C032UNIUMC] ,[N032TIPRSA],[C032REQSA]
			   ,[C032CERSA] ,[C032PAISOR] ,[C032PAISPR] ,[F032VALMER] ,[C032PLANTA] ,[C032CVEUNI]
			   ,[I032NUMCAR] ,[N032ORGGEN] ,[PREF] ,[C032NOMLAB] ,[C032DESPRO]
			   ,[C032VARPRO] ,[C032CANMUE] ,[C032CLAVELABOR] ,[C032TIPOLABORA] ,[C032ORDEN])
	SELECT    C032SECFRA,@Referencia ,C032FRAC,C032DESCR,C032USOPRO
			   ,F032CANUMT ,C032UNIUMT ,F032CANUMC ,C032UNIUMC ,N032TIPRSA,C032REQSA
			   ,C032CERSA ,C032PAISOR ,C032PAISPR ,F032VALMER ,C032PLANTA ,C032CVEUNI
			   ,I032NUMCAR ,N032ORGGEN ,PREF ,C032NOMLAB ,C032DESPRO
			   ,C032VARPRO ,C032CANMUE ,C032CLAVELABOR ,C032TIPOLABORA ,C032ORDEN
	FROM SAGARD where C032REFPED = @REFORG and pref=@PREF

	--Insertar SAGARDLAB
	print 'SAGARDLAB'
	INSERT INTO SAGARdlab ([C034ADUSEC]  ,[C034REFPED] ,[C034SECFRA] ,[C034FRAC]  ,[C034NUMOIF] ,[C034TIPLAB]
			   ,[C034NOMLAB] ,[C034CVELAB] ,[C034DESPRO] ,[C034USOPRO] ,[C034VARPRO] ,[C034CANMUE] ,[C034REQFAC]
			   ,[C034FECPAG] ,[F032MONPAG] ,[C034NUMCIE] ,[C034NOMFAC] ,[C034RFCFAC] ,[C034CALFAC] ,[C034NUMFAC]
			   ,[C034COLFAC] ,[C034CPFAC]  ,[C034ESTFAC] ,[C034MUNFAC] ,[C034TELFAC] ,[C034LADFAC] ,[C034PAIFAC]
			   ,[C034NUMCUE] ,[PREF] ,[D034FECOPER])
	SELECT [C034ADUSEC]  ,@Referencia ,[C034SECFRA] ,[C034FRAC]  ,[C034NUMOIF] ,[C034TIPLAB]
			   ,[C034NOMLAB] ,[C034CVELAB] ,[C034DESPRO] ,[C034USOPRO] ,[C034VARPRO] ,[C034CANMUE] ,[C034REQFAC]
			   ,[C034FECPAG] ,[F032MONPAG] ,[C034NUMCIE] ,[C034NOMFAC] ,[C034RFCFAC] ,[C034CALFAC] ,[C034NUMFAC]
			   ,[C034COLFAC] ,[C034CPFAC]  ,[C034ESTFAC] ,[C034MUNFAC] ,[C034TELFAC] ,[C034LADFAC] ,[C034PAIFAC]
			   ,[C034NUMCUE] ,[PREF] ,[D034FECOPER]
	FROM SAGARDLAB where C034REFPED=@REFORG and pref=@PREF

	--Insertar SAGARDLotes
	print 'SAGARDLotes'
	INSERT INTO [SAGARdlotes] ([C033SECFRA] ,[C033REFPED] ,[C033FRAC] ,[C033LOTE] ,[C033CLASIF] ,[D033FECEMP] ,[D033FECSAC]
			   ,[D033FECCAD] ,[D033FECELA] ,[N033CONSE] ,[PREF] ,[TIPO_LOTE] ,[C033LOTE_FIN])
	SELECT C033SECFRA ,@Referencia ,C033FRAC ,C033LOTE ,C033CLASIF ,D033FECEMP ,D033FECSAC
			   ,D033FECCAD ,D033FECELA ,N033CONSE ,PREF ,TIPO_LOTE ,C033LOTE_FIN
	FROM SAGARDlotes where C033REFPED=@REFORG and pref=@PREF

	SELECT @Referencia

	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
		PRINT 'ERROR'
		PRINT 'ERROR_NUMBER: ' + CONVERT(VARCHAR,ERROR_NUMBER())
		PRINT 'ERROR_SEVERITY: ' + CONVERT(VARCHAR,ERROR_SEVERITY())
		PRINT 'ERROR_STATE: ' + CONVERT(VARCHAR,ERROR_STATE())
		PRINT 'ERROR_LINE: ' + CONVERT(VARCHAR,ERROR_LINE())
		PRINT 'ERROR_PROCEDURE: ' + ERROR_PROCEDURE()
		PRINT 'ERROR_MESSAGE: ' + ERROR_MESSAGE()
		
		ROLLBACK TRANSACTION
	
		SET @Error = ERROR_MESSAGE();
		RAISERROR (@Error,19,1); 
END CATCH;	
END;
GO
