-- =============================================
-- AUTHOR     : LEONEL GONZALEZ
-- DATE       :
-- DESCRIPTION:
-- =============================================
USE [Aduana]
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'smidashboard_sps_validacfdixml' AND TYPE = 'P')
	  DROP PROCEDURE smidashboard_sps_validacfdixml;
GO
CREATE PROCEDURE smidashboard_sps_validacfdixml(@XmlFile NVARCHAR(MAX))
WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @XmlCFDI XML = CAST(@XmlFile AS XML)
	DECLARE @EMISORRFC VARCHAR(13),@EMISORNOMBRE VARCHAR(150),@CLIENTENOM VARCHAR(150),@CLIENTENUM VARCHAR(15),@CLIENTE_ID INT=0
	SELECT
		 @EMISORRFC=T.C.value('@rfc', 'varchar(13)')
		,@EMISORNOMBRE=T.C.value('@nombre', 'varchar(150)')
	from @XmlCFDI.nodes('declare namespace cfdi="http://www.sat.gob.mx/cfd/3"; //cfdi:Comprobante/cfdi:Emisor') T(C)

	DECLARE @RECEPTORRFC VARCHAR(13),@RECEPTORNOMBRE VARCHAR(150)
	SELECT
		 @RECEPTORRFC=T.C.value('@rfc', 'varchar(13)')
		,@RECEPTORNOMBRE=T.C.value('@nombre', 'varchar(150)')
	from @XmlCFDI.nodes('declare namespace cfdi="http://www.sat.gob.mx/cfd/3"; //cfdi:Comprobante/cfdi:Receptor') T(C)

	DECLARE @UUID VARCHAR(40)
	SELECT
		 @UUID=T.C.value('@UUID', 'varchar(40)')
	from @XmlCFDI.nodes('declare namespace cfdi="http://www.sat.gob.mx/cfd/3"; //cfdi:Comprobante/cfdi:Complemento/cfdi:TimbreFiscalDigital') T(C)

	DECLARE @CONCEPTOS TABLE(
	 id INT IDENTITY(1,1)
	,cantidad FLOAT
	,unidad VARCHAR(10)
	,noIdentificacion VARCHAR(20)
	,descripcion VARCHAR(250)
	,valorUnitario FLOAT	
	,importe FLOAT) 
	INSERT INTO @CONCEPTOS(cantidad,unidad,noIdentificacion,descripcion,valorUnitario,importe)
	SELECT
		  T.C.value('@cantidad', 'float')
		 ,T.C.value('@unidad', 'varchar(10)')
		 ,T.C.value('@noIdentificacion', 'varchar(20)')
		 ,T.C.value('@descripcion', 'varchar(250)')
		 ,T.C.value('@valorUnitario', 'float')
		 ,T.C.value('@importe', 'float')
	from @XmlCFDI.nodes('declare namespace cfdi="http://www.sat.gob.mx/cfd/3"; //cfdi:Comprobante/cfdi:Conceptos/cfdi:Concepto') T(C)

	DECLARE @BKLINE VARCHAR(6)='<br />', @HTMLLOG VARCHAR(MAX)=''
	
	SET @HTMLLOG += '<h3>INICIO DEL PROCESO</h3>'+@BKLINE
	
	SET @HTMLLOG += 'VALIDANDO DATOS DE EMISOR: '+@EMISORNOMBRE+@BKLINE

	IF EXISTS(SELECT CLIENTE_ID FROM CLIENTES WHERE RFC=@EMISORRFC) BEGIN
	    SELECT @CLIENTENOM=ISNULL(NOM,''),@CLIENTENUM=ISNULL(NUMERO,''),@CLIENTE_ID=ISNULL(CLIENTE_ID,0) FROM CLIENTES WHERE RFC=@EMISORRFC
		SET @HTMLLOG += '<strong>--EL EMISOR SE ENCUENTRA EN LA BASE DE DATOS COMO: '+@CLIENTENOM+'</strong>'+@BKLINE
		SET @HTMLLOG += '<strong>--CLIENTE ID: '+CONVERT(VARCHAR,@CLIENTE_ID)+'</strong>'+@BKLINE
		SET @HTMLLOG += '<strong>--CLIENTE NUMERO: '+@CLIENTENUM+'</strong>'+@BKLINE
	END
	ELSE BEGIN
		SET @EMISORNOMBRE=SUBSTRING(@EMISORNOMBRE , 1, CHARINDEX(' ', @EMISORNOMBRE ) - 1);
		SET @HTMLLOG += '<font color="red">----NO SE ECONTRARON REGISTROS EN LA BASE DE DATOS</font>'+@BKLINE
		SET @HTMLLOG += '--POSIBLES COINCIDENCIAS'+@BKLINE

		DECLARE @concatenatedCLI NVARCHAR(1000)
		SET @concatenatedCLI = @BKLINE
		SELECT @concatenatedCLI = @concatenatedCLI + clientes.nom + @BKLINE  FROM CLIENTES WHERE NOM LIKE '%'+@EMISORNOMBRE+'%'
		SET @HTMLLOG += @concatenatedCLI

		SET @HTMLLOG += @BKLINE
	END

	SET @HTMLLOG += @BKLINE

	DECLARE @PRONOM VARCHAR(150)='',@PRONUM VARCHAR(15), @PROVEEDOR_ID INT=0
	SET @HTMLLOG += 'VALIDANDO DATOS DE RECEPTOR: '+@RECEPTORNOMBRE+@BKLINE
	SET @HTMLLOG += '--VALIDANDO POR TAXID'+@BKLINE
	IF EXISTS(SELECT PROVEEDOR_ID FROM PROCLI WHERE PROIRS=@RECEPTORRFC) BEGIN
		SELECT @PRONOM=ISNULL(PRONOM,''),@PRONUM=ISNULL(NUMERO,''),@PROVEEDOR_ID=PROVEEDOR_ID FROM PROCLI WHERE PROIRS=@RECEPTORRFC
		SET @HTMLLOG += '<strong>--EL RECEPTOR SE ENCUENTRA EN LA BASE DE DATOS COMO: '+@PRONOM+'</strong>'+@BKLINE
		SET @HTMLLOG += '<strong>--PROVEDOR ID: '+CONVERT(VARCHAR,@PROVEEDOR_ID)+'</strong>'+@BKLINE
		SET @HTMLLOG += '<strong>--PROVEEDOR NUMERO: '+@PRONUM+'</strong>'+@BKLINE
    END 
	ELSE
		SET @HTMLLOG += '<font color="red">----NO SE ENCONTRARON RESULTADOS, VALIDANDO POR NOMBRE</font>'+@BKLINE

	IF @PRONOM='' BEGIN
		IF EXISTS(SELECT PROVEEDOR_ID FROM PROCLI WHERE PRONOM=@RECEPTORNOMBRE) BEGIN
			SELECT  @PRONOM=ISNULL(PRONOM,''),@PRONUM=ISNULL(NUMERO,''),@PROVEEDOR_ID=PROVEEDOR_ID  FROM PROCLI WHERE PRONOM=@RECEPTORNOMBRE
			SET @HTMLLOG += '--EL RECEPTOR SE ENCUENTRA EN LA BASE DE DATOS COMO: '+@PRONOM+@BKLINE
			SET @HTMLLOG += '<strong>--PROVEDOR ID: '+CONVERT(VARCHAR,@PROVEEDOR_ID)+'</strong>'+@BKLINE
			SET @HTMLLOG += '<strong>--PROVEEDOR NUMERO: '+@PRONUM+'</strong>'+@BKLINE
		END
		ELSE
			SET @HTMLLOG += '<font color="red">----NO SE ENCONTRARON RESULTADOS, BUSCANDO POSIBLES COINCIDENCIAS</font>'+@BKLINE
	END

	IF @PRONOM='' BEGIN
		SET @RECEPTORNOMBRE=SUBSTRING(@RECEPTORNOMBRE , 1, CHARINDEX(' ', @RECEPTORNOMBRE ) - 1);
		SET @HTMLLOG += '----POSIBLES COINCIDENCIAS'+@BKLINE
		DECLARE @concatenated NVARCHAR(1000)
		SET @concatenated = @BKLINE
		SELECT @concatenated = @concatenated + procli.pronom + @BKLINE  FROM procli WHERE pronom LIKE '%'+@RECEPTORNOMBRE+'%'
		SET @HTMLLOG += @concatenated

		SET @HTMLLOG += @BKLINE
	END
	SET @HTMLLOG += @BKLINE

	SET @HTMLLOG += '--VALIDANDO REGISTROS DE PARTIDAS'+@BKLINE
	DECLARE @i INT=(SELECT COUNT(*) FROM @CONCEPTOS),@x INT=1
	DECLARE @PARTNUM VARCHAR(25), @PARTDESC VARCHAR(250)
	WHILE @x<=@I BEGIN
		SELECT @PARTNUM=ISNULL(noIdentificacion,''),@PARTDESC=ISNULL(descripcion,'') FROM @CONCEPTOS WHERE ID=@x
		SET @HTMLLOG += @BKLINE
		SET @HTMLLOG += '--PARTIDA NUMERO: '+CONVERT(VARCHAR,@x)+@BKLINE
		SET @HTMLLOG += '--NUMERO DE PARTE: '+@PARTNUM+@BKLINE
		SET @HTMLLOG += '--DESCRIPCION: '+@PARTDESC+@BKLINE
		--SELECT @PARTNUM,@PARTDESC
		IF @PARTNUM='' BEGIN
			SET @HTMLLOG += '--SIN NUMERO DE PARTE BUSCANDO POR DESCRIPCION'+@BKLINE
			IF EXISTS(SELECT PARTNUM FROM TBLPARTES WHERE PARTCLI=@CLIENTE_ID AND partdescesp=@PARTDESC) BEGIN
				SET @HTMLLOG += '<strong>--SI SE ENCONTRARON REGISTROS CON DESCRIPCION: '+@PARTDESC+'</strong>'+@BKLINE
			END
			ELSE
				SET @HTMLLOG += '<font color="red">----NO SE ENCONTRARON RESULTADOS</font>'+@BKLINE
		END
		ELSE BEGIN
			IF EXISTS(SELECT PARTNUM FROM TBLPARTES WHERE PARTCLI=@CLIENTE_ID AND PARTNUM=@PARTNUM) BEGIN
				SET @HTMLLOG += '<strong>--SI SE ENCONTRARON REGISTROS DEL CLIENTE CON NUMERO DE PARTE: '+@PARTNUM+'</strong>'+@BKLINE
			END
			ELSE
				SET @HTMLLOG += '<font color="red">----NO SE ENCONTRARON RESULTADOS</font>'+@BKLINE
		END

		SET @x +=1;
	END

	SET @HTMLLOG += '<strong>FIN DEL PROCESO</strong>'+@BKLINE

	IF @PROVEEDOR_ID=0 BEGIN	
		SET @PROVEEDOR_ID=4131
		SET @PRONOM=(SELECT PRONOM FROM PROCLI WHERE PROVEEDOR_ID=@PROVEEDOR_ID)
    END 

	SELECT @HTMLLOG HTMLLOG, @CLIENTE_ID cliente_id, @PROVEEDOR_ID proveedor_id, @PRONOM pronom, @UUID uuid
	    

END
GO
GRANT EXEC ON smidashboard_sps_validacfdixml TO PUBLIC;
GO
