-- =============================================
-- AUTHOR     : LEONEL GONZALEZ
-- DATE       :
-- DESCRIPTION:
-- =============================================
USE [Aduana]
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'smidashboard_sps_loadcfdirefs' AND TYPE = 'P')
	  DROP PROCEDURE smidashboard_sps_loadcfdirefs;
GO
CREATE PROCEDURE smidashboard_sps_loadcfdirefs
(@cliente_id INT 
,@tipo INT)
WITH ENCRYPTION
AS
BEGIN
	
	IF @tipo=1 BEGIN
		SELECT  
			TRAFICO.TRAFICO_ID
	       ,TRAFICO.TRAREFERENCIA [REFERENCIA]
	       ,CONVERT(VARCHAR,TBLBOD.BODFECHA+ISNULL(TBLBOD.BODHORA,''),120) [FECHA]
		   ,TRAFICO.TRAPEDIMENTO [PEDIMENTO]
		   ,TRAFICO.TRAADUANA [ADUANA]
		FROM TBLBOD       
		LEFT JOIN TRAFICO ON TRAFICO.TRAREFERENCIA = TBLBOD.BODREFERENCIA
		WHERE TRAFICO.TRACLI=@CLIENTE_ID
		AND TRAFICO.TRAFECHACRUCE IS NULL
		AND TBLBOD.BODVIRTUAL = 0 
		AND TRAFICO.TRAIMPEXP=0
	END
	ELSE BEGIN
		DECLARE @MASTER VARCHAR(10)=(SELECT TOP(1)BODREFERENCIA 
							FROM TBLBOD 
							WHERE BODCLI=@cliente_id
							AND CONVERT(VARCHAR,TBLBOD.BODFECHA,101)=DATEADD(WK, DATEDIFF(WK,0,GETDATE()), 0)
							ORDER BY BODHORA)
	    DECLARE @IDOPERACION INT=(SELECT ID_OPERACION FROM DBO.REMESAS_GEN WHERE REFERENCIA=@MASTER)
		
		SELECT  TRAFICO.TRAFICO_ID
			   ,REMESAS_GEN.REFERENCIA
			   ,REMESAS_GEN.FECHA_CREACION [FECHA] 
			   ,TRAFICO.TRAPEDIMENTO [PEDIMENTO]
			   ,TRAFICO.TRAADUANA [ADUANA]
			   ,REMESAS_DET.NUMERO_REMESA [REMESA]
		FROM REMESAS_GEN
		LEFT JOIN REMESAS_DET ON REMESAS_DET.ID_REMESA = REMESAS_GEN.ID_REMESA
		LEFT JOIN TRAFICO ON TRAFICO.TRAREFERENCIA=REMESAS_GEN.REFERENCIA       
		WHERE REMESAS_GEN.ID_OPERACION=@IDOPERACION
		ORDER BY REMESAS_DET.NUMERO_REMESA

	END
	   
END
GO
GRANT EXEC ON smidashboard_sps_loadcfdirefs TO PUBLIC;
GO
