-- =============================================
-- AUTHOR     : LEONEL GONZALEZ
-- DATE       :
-- DESCRIPTION:
-- =============================================
USE [Aduana]
IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME = 'smidashboard_spi_processxmllayout_new' AND TYPE = 'P')
	  DROP PROCEDURE smidashboard_spi_processxmllayout_new;
GO
CREATE PROCEDURE smidashboard_spi_processxmllayout_new(@REF VARCHAR(10), @XmlFile XML)
WITH ENCRYPTION
AS
BEGIN

BEGIN TRY
	BEGIN TRANSACTION

	ALTER TABLE tblclasifica DISABLE TRIGGER lock_tblclasifica
	ALTER TABLE tblfactgen DISABLE TRIGGER aviso_ctestblfactgen


		DECLARE @CLIENTE_ID INT, @PROVEEDOR_ID INT, @PREF VARCHAR(8), @TIPOOP BIT
	
		IF NOT EXISTS(SELECT TRAREFERENCIA FROM TRAFICO WHERE TRAREFERENCIA=@REF) BEGIN
			RAISERROR ('LA REFERENCIA NO EXISTE', 16, 1); 
		END
		ELSE BEGIN
			SELECT @CLIENTE_ID=TRACLI, @PROVEEDOR_ID=TRAPROCLI, @PREF=PREF, @TIPOOP=TRAIMPEXP FROM TRAFICO WHERE TRAREFERENCIA=@REF
		END
	
	
		DECLARE @FULLXML XML
		SET @FULLXML=@XmlFile;
	
		DECLARE @CONCEPTOS TABLE(
		 ID INT IDENTITY(1,1),CLIENTE INT,COMPRADOR INT,DESTINATARIO INT,FACTURA VARCHAR(50),FECHA DATETIME,PAISFAC VARCHAR(3),INCOTERM VARCHAR(3),MV INT
		,VIN INT,FLETES FLOAT,EMBALAJES FLOAT,SEGUROS FLOAT,OTROS FLOAT,VALOR_FACTURA FLOAT,MONEDA VARCHAR(3),NO_COVE VARCHAR(10),SUBDIVISION_COVE INT
		,OBSERVACIONES_COVE VARCHAR(200),PEDIDO VARCHAR(50),LN INT,PARTE VARCHAR(30),FRACCION VARCHAR(8),GRUPO VARCHAR (10),DESC_INGLES VARCHAR(250)
		,DESC_ESPANOL VARCHAR(250),ORIGEN VARCHAR(3),TLC VARCHAR(1),PROSEC VARCHAR(1),MA VARCHAR(1),UMFO VARCHAR(3),CANTIDAD_UMFO FLOAT,UMC VARCHAR(3)	
		,CANTIDAD_UMC FLOAT	,CANTIDAD_UMT FLOAT,PESO_LBS FLOAT,PESO_KGS FLOAT,PRECIO_UNITARIO FLOAT,TOTAL FLOAT,VALOR_AGREGADO FLOAT,MARCA VARCHAR(10)
		,MODELO VARCHAR(50),SERIE VARCHAR(50),OBSERVACIONES VARCHAR(200),FACTURA_ID NUMERIC(10),PARTIDA_ID NUMERIC(10),CLASIFICADA BIT, UMT VARCHAR(3),IVA FLOAT, IGI FLOAT)

		INSERT INTO @CONCEPTOS(CLIENTE,COMPRADOR,DESTINATARIO,FACTURA,FECHA,PAISFAC,INCOTERM,MV,VIN,FLETES,EMBALAJES,SEGUROS,OTROS,VALOR_FACTURA,MONEDA,NO_COVE,SUBDIVISION_COVE,
							   OBSERVACIONES_COVE,PEDIDO,LN,PARTE,FRACCION,GRUPO,DESC_INGLES,DESC_ESPANOL,ORIGEN,TLC,PROSEC,MA,UMFO,CANTIDAD_UMFO,UMC,CANTIDAD_UMC,
							   CANTIDAD_UMT,PESO_LBS,PESO_KGS,PRECIO_UNITARIO,TOTAL,VALOR_AGREGADO,MARCA,MODELO,SERIE,OBSERVACIONES)
		SELECT 
			 T.c.value('F1[1]','int')
			,T.c.value('F2[1]','int')
			,T.c.value('F3[1]','int')
			,T.c.value('F4[1]','varchar(50)')
			,T.c.value('F5[1]','datetime')
			,T.c.value('F6[1]','varchar(3)')
			,T.c.value('F7[1]','varchar(3)')
			,T.c.value('F8[1]','int')
			,T.c.value('F9[1]','int')
			,T.c.value('F10[1]','float')
			,T.c.value('F11[1]','float')
			,T.c.value('F12[1]','float')
			,T.c.value('F13[1]','float')
			,T.c.value('F14[1]','float')
			,T.c.value('F15[1]','varchar(3)')
			,T.c.value('F16[1]','varchar(10)')
			,T.c.value('F17[1]','int')
			,T.c.value('F18[1]','varchar(200)')
			,T.c.value('F19[1]','varchar(50)')
			,T.c.value('F20[1]','int')
			,T.c.value('F21[1]','varchar(30)')
			,T.c.value('F22[1]','varchar(8)')
			,T.c.value('F23[1]','varchar(10)')
			,T.c.value('F24[1]','varchar(250)')
			,T.c.value('F25[1]','varchar(250)')
			,T.c.value('F26[1]','varchar(3)')
			,T.c.value('F27[1]','varchar(1)')
			,T.c.value('F28[1]','varchar(1)')
			,T.c.value('F29[1]','varchar(1)')
			,T.c.value('F30[1]','varchar(3)')
			,T.c.value('F31[1]','float')
			,T.c.value('F32[1]','varchar(3)')
			,T.c.value('F33[1]','float')
			,T.c.value('F34[1]','float')
			,T.c.value('F35[1]','float')
			,T.c.value('F36[1]','float')
			,T.c.value('F37[1]','float')
			,T.c.value('F38[1]','float')
			,T.c.value('F39[1]','float')
			,T.c.value('F40[1]','varchar(10)')
			,T.c.value('F41[1]','varchar(50)')
			,T.c.value('F42[1]','varchar(50)')
			,T.c.value('F43[1]','varchar(200)')
		FROM   @FULLXML.nodes('/NewDataSet/Table') T(c)	
		ORDER BY T.c.value('F4[1]','varchar(50)')

		IF (SELECT COUNT(*) FROM @CONCEPTOS)=0 BEGIN
			RAISERROR ('LA NO SE ENCONTRO INFORMACION EN EL ARCHIVO O LAYOUT INVALIDO', 16, 1); 
		END		
		------------------------------------------------------
		    DELETE FROM @CONCEPTOS WHERE ISNULL(FACTURA,'')=''
		------------------------------------------------------
		DECLARE @FACTURAS TABLE(
			 ID INT IDENTITY(1,1),FACTURA_ID NUMERIC(10),FACGNOFAC VARCHAR(50),FACGREF VARCHAR(10),FACGFEFAC DATETIME,FACGVALOR FLOAT,FACGMONEDA VARCHAR(3)
			,FACGPAIS VARCHAR(3),FACGPROV INT,FACGCLI INT,FACGVALORMERC FLOAT,FACGSUBDIVISION INT,FACGUSUARIO INT,PREF VARCHAR(8),FACGBANDERA BIT
			,FACGCLASIFICADA BIT,FACGSUCURSAL INT,NOMOSTRARENINVENTARIO BIT,VIN VARCHAR(1),FACGINCOTERM VARCHAR(3),SMIFACCFDI BIT,SMIFACELECTRONICA BIT)

		INSERT INTO @FACTURAS(FACTURA_ID,FACGNOFAC,FACGREF,FACGFEFAC,FACGVALOR,FACGMONEDA,FACGPAIS ,FACGPROV ,FACGCLI ,FACGVALORMERC ,FACGSUBDIVISION ,FACGUSUARIO ,
							  PREF,FACGBANDERA ,FACGCLASIFICADA ,FACGSUCURSAL ,NOMOSTRARENINVENTARIO ,VIN ,FACGINCOTERM ,SMIFACCFDI ,SMIFACELECTRONICA)
		SELECT 0,ISNULL(FACTURA,GETDATE()),@REF,FECHA,0,MONEDA,PAISFAC,@PROVEEDOR_ID,@CLIENTE_ID,0,0,0,@PREF,0,1,0,0,0,'',0,1 
		FROM @CONCEPTOS 
		GROUP BY FACTURA,FECHA,MONEDA,PAISFAC
		ORDER BY FACTURA
	
		DECLARE @x INT=1, @TOTALFACTURAS INT = (SELECT COUNT(*) FROM @FACTURAS)
		DECLARE @FACTURA_ID NUMERIC(10),@FACTURA VARCHAR(50),@TOTALFACTURA FLOAT;

		------------------------------------------------------
			DELETE FROM TBLFACTGEN WHERE FACGREF=@REF AND PREF=@PREF;
		------------------------------------------------------

		WHILE @x<=@TOTALFACTURAS BEGIN
			
			SET @TOTALFACTURA=(SELECT SUM(VALOR_FACTURA) FROM @CONCEPTOS WHERE FACTURA=(SELECT FACGNOFAC FROM @FACTURAS WHERE ID=@x))
			
			INSERT INTO TBLFACTGEN(FACGFEFAC,FACGNOFAC,FACGREF,FACGVALOR,FACGMONEDA,FACGPAIS ,FACGPROV ,FACGCLI ,FACGVALORMERC ,FACGSUBDIVISION ,FACGUSUARIO ,
							  PREF,FACGBANDERA ,FACGCLASIFICADA ,FACGSUCURSAL ,NOMOSTRARENINVENTARIO ,VIN ,FACGINCOTERM ,SMIFACCFDI ,SMIFACELECTRONICA)
			SELECT ISNULL(FACGFEFAC,GETDATE()),FACGNOFAC,FACGREF,@TOTALFACTURA,FACGMONEDA,FACGPAIS ,FACGPROV ,FACGCLI ,@TOTALFACTURA ,FACGSUBDIVISION ,FACGUSUARIO ,
					PREF,FACGBANDERA ,FACGCLASIFICADA ,FACGSUCURSAL ,NOMOSTRARENINVENTARIO ,VIN ,FACGINCOTERM ,SMIFACCFDI ,SMIFACELECTRONICA
			FROM @FACTURAS WHERE ID=@x;

			SET @FACTURA_ID=@@IDENTITY;			
			UPDATE @FACTURAS SET FACTURA_ID=FACTURA_ID WHERE ID=@x;
			
			SELECT @FACTURA=FACGNOFAC FROM @FACTURAS WHERE ID=@x;	
			UPDATE @CONCEPTOS SET FACTURA_ID=@FACTURA_ID WHERE FACTURA=@FACTURA;
			
			SET @x=@x+1;
		END

		------------------------------------------------------
			DELETE FROM TBLCLASIFICA WHERE REFERENCIA=@REF;
		------------------------------------------------------

		DECLARE @PARTNUM VARCHAR(100)
		DECLARE @I INT=(SELECT COUNT(*) FROM @CONCEPTOS)
		SET @x=1
		WHILE @x<=@I BEGIN
			
			INSERT INTO TBLCLASIFICA(FACTURA_ID,FACTURA,REFERENCIA,RENGLON,NUMPARTE,DESCFRA,CANTIDAD,CANTFAC,CANTTAR,PESOLBS,PESOKGS
									,PREUNITARIO,TOTAL,CC,VPR,USUARIO,NUMFRACCION,FECHA,ULTIMA_MOD,PAISORIGEN,UNIMEDFAC
									,UA,TLC,PROSEC,MA,INDUSTRIA,CLAVE1) 
			SELECT FACTURA_ID,FACTURA,@REF,LN,PARTE,DESC_ESPANOL,CANTIDAD_UMFO,CANTIDAD_UMC,CANTIDAD_UMT,PESO_KGS/0.4536,PESO_KGS
				,TOTAL/CANTIDAD_UMFO,TOTAL,0,0,1,FRACCION,GETDATE(),GETDATE(),ORIGEN,UMC,UMFO,TLC,PROSEC,'N','',GRUPO 
			FROM @CONCEPTOS WHERE ID=@x;

			SET @FACTURA_ID=(SELECT FACTURA_ID FROM @CONCEPTOS WHERE ID=@x);
			SET @PARTNUM=(SELECT PARTE FROM @CONCEPTOS WHERE ID=@x);

			IF EXISTS(SELECT PARTNUM FROM TBLPARTES WHERE PARTNUM=@PARTNUM AND PARTCLI=@CLIENTE_ID) BEGIN
				UPDATE TBLCLASIFICA SET 
				 NUMFRACCION=TBLPARTES.PARTFRAMEX
				,PAISORIGEN=TBLPARTES.PARTPAIS
				,UA=TBLPARTES.PARTMEDIDA
				,UNIMEDFAC=TBLPARTES.PARTMEDIDA
				,DESCFRA=TBLPARTES.PARTDESCESP
				,TLC=TBLPARTES.PARTTLC
				,PROSEC=TBLPARTES.PROSEC
				FROM TBLCLASIFICA
				LEFT JOIN TBLPARTES ON PARTCLI=@CLIENTE_ID AND TBLPARTES.PARTNUM=TBLCLASIFICA.NUMPARTE
				WHERE FACTURA_ID=@FACTURA_ID;

				UPDATE @CONCEPTOS SET CLASIFICADA=1 WHERE ID=@x;
			END
			ELSE BEGIN
				UPDATE @CONCEPTOS SET CLASIFICADA=0 WHERE ID=@x;
			END

			UPDATE TBLCLASIFICA SET UMFAC=TBLUDC.CLAVE
			FROM TBLCLASIFICA
			LEFT JOIN TBLUDC ON TBLUDC.ABREVIACION=TBLCLASIFICA.UA
			WHERE FACTURA_ID=@FACTURA_ID;

			UPDATE TBLCLASIFICA SET UMUMF=TBLUNIDAD.CLAVE
			FROM TBLCLASIFICA
			LEFT JOIN TBLUNIDAD ON TBLUNIDAD.ABREVIACION=TBLCLASIFICA.UNIMEDFAC
			WHERE FACTURA_ID=@FACTURA_ID;
			
			IF @TIPOOP=0 BEGIN
				UPDATE TBLCLASIFICA SET 
				 IVA=0.00,
				 UNIMEDTAR=(CASE WHEN UPPER(UNID_TRF)='L' THEN 'LTR'
							  WHEN UPPER(UNID_TRF)='M²' THEN 'M2'
							  ELSE UPPER(UNID_TRF)END),
				 ADV=0
				 FROM TBLCLASIFICA 
				 LEFT JOIN EXPORTA ON EXPORTA.FRACCION=TBLCLASIFICA.NUMFRACCION
				 WHERE FACTURA_ID=@FACTURA_ID;

			END
			ELSE BEGIN
				UPDATE TBLCLASIFICA SET 
				 IVA=CASE WHEN PGA_IVA = 'N' THEN 0.00
						  WHEN ISNULL(PGA_IVA,'X') = 'X' THEN ISNULL((SELECT TOP 1 IVAEUA FROM TBLCOMP WHERE PREF = @PREF),0.00)
					 END,
				 UNIMEDTAR=(CASE WHEN UPPER(UNID_TRF)='L' THEN 'LTR'
							  WHEN UPPER(UNID_TRF)='M²' THEN 'M2'
							  ELSE UPPER(UNID_TRF)END),
				 ADV=0
				 FROM TBLCLASIFICA 
				 LEFT JOIN IMPORTA ON IMPORTA.FRACCION=TBLCLASIFICA.NUMFRACCION
				 WHERE FACTURA_ID=@FACTURA_ID;
			END

			UPDATE TBLCLASIFICA SET CANTTAR=PESOKGS
			FROM TBLCLASIFICA
			WHERE FACTURA_ID=@FACTURA_ID AND UNIMEDTAR='KG';

			SET @x +=1;
		END

    ALTER TABLE tblclasifica DISABLE TRIGGER lock_tblclasifica
	ALTER TABLE tblfactgen DISABLE TRIGGER aviso_ctestblfactgen	
	
	SELECT * FROM @CONCEPTOS   
	COMMIT TRANSACTION

END TRY
BEGIN CATCH
    DECLARE @ErrorMessage NVARCHAR(4000)=ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT=ERROR_SEVERITY();
    DECLARE @ErrorState INT=ERROR_STATE();

    ALTER TABLE tblclasifica DISABLE TRIGGER lock_tblclasifica
	ALTER TABLE tblfactgen DISABLE TRIGGER aviso_ctestblfactgen

    ROLLBACK TRANSACTION

    RAISERROR (@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH	
	
			    
END
GO
GRANT EXEC ON smidashboard_spi_processxmllayout_new TO PUBLIC;
GO
